### ISSUE TITLE
"this & object prototypes": Chapter 2 'Explicit Binding' - question about explicit binding losing the "this" binding

### ISSUE THREAD

**Issue by robbporto** [getify/You-Dont-Know-JS#1031]
In this chapter, it's said:

> Unfortunately, explicit binding alone still doesn't offer any solution to the issue mentioned previously, of a function "losing" its intended this binding, or just having it paved over by a framework, etc.

Can you do a quick example of explicit binding losing the `this` binding?

**Comment by getify** [comment]
Explicit binding is something you do with a function at a call site... that doesn't affect how any other invocation of your function might work.

```js
function f() { return this.id; }

f.call( {id:42} );   // 42 (explicit binding)

// later

f();   // undefined (not explicit binding)
```

**Comment by StephenVNelson** [comment]
I will just add that I was very confused with the wording "explicit binding alone still doesn't offer any solution the issue mentioned previously" because "the issue that was mentioned previously" is about losing an intended implicit binding, but in fact, whenever you use the .call you are guaranteeing that you are binding to the object that is passed as a parameter... So it does seem to solve that issue. So either
1) I am confused about what exactly is "the issue mentioned previously"
2) You're actually talking about a new issue, which is wanting to guarantee that binding in the form of a function call by making a helper function or something...
