### ISSUE TITLE
Implicitly * --> Boolean (demo confusion?)

### ISSUE THREAD

**Issue by Danilux** [getify/You-Dont-Know-JS#1133]
In the last example, the // yep makes it look like the if executes, but the expression ((a && d) || c) evaluates to false
```
if ((a && d) || c) {
	console.log( "yep" );		// yep
}
```

**Comment by lalosh** [comment]
here's the full code
```js

var a = 42;
var b = "abc";
var c;
var d = null;

if (a) {
	console.log( "yep" );		// yep
}

while (c) {
	console.log( "nope, never runs" );
}

c = d ? a : b;
c;					// "abc"

if ((a && d) || c) {
	console.log( "yep" );		// yep
}

```
let's discuss in details what ( (a&&b) || c) is doing and what if is doing
a = 42
d = null
c = "abc"

a && d => will give d because a is truthy
d || c => will give c because d is falsy
now c is "abc" 

we have if(c) and while c is truthy(not on the falsy list) => c is evaluated to true and "yep" is printed.

please consider re-reading [operator || and &&] if you didn't get the hang of it for now
https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch4.md#operators--and-

**Comment by getify** [comment]
```js
c = d ? a : b;
c;					// "abc"
```

That line clearly shows that `c` is `"abc"`. Therefore:

```js
((a && d) || c)   // "abc"
```

And is thus truthy. You have to read the whole snippet, not only a few lines.
