### ISSUE TITLE
Concise (shorthand) method is named or anonymous?

### ISSUE THREAD

**Issue by jesseminn** [getify/You-Dont-Know-JS#1161]
In [this part](https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20%26%20beyond/ch2.md#concisely-unnamed), it is mentioned that concise method is anonymous, but I found the definition on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions):
> The shorthand syntax uses **named function** instead of anonymous functions (as in …foo: function() {}…).

But I tried the given code example in Chrome devtool and **did** get `ReferenceError`:
```js
function runSomething(o) {
	var x = Math.random(),
		y = Math.random();

	return o.something( x, y );
}

runSomething( {
	something(x,y) {
		if (x > y) {
			return something( y, x );
		}

		return y - x;
	}
} );
```

I also tried shorthand method in Babel, and it's transpiled into *named* method:
```js
const o = {
  foo() {console.log('foo')}
}
```
transpiled into
```js
var o = {
	foo: function foo() {
		console.log('foo');
	}
};
```

If the shorthand method is named (like MDN said), I should not get an error...it's really confusing to me now. Could you explain this for me? Thank you!

**Comment by getify** [comment]
Concise methods are indeed lexically anonymous. MDN is wrong. Babel (in your simple case) is misleading. Try [this code in Babel](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBA9hC8EG8BQFUDMpQBQA8CUiKqxAlmhLhAHwQDMBYApgC4CuYAdhBtjhAPQQATHgDcRYhCZtOEHOOIBfJIvFIoAOh5YAjAAYxQA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0) and see:

```js
var o = {
   foo(x) {
      if (x > 3) return foo(x / 2);
      return x;
   }
};

o.foo(10);
```

You'll see that in both the console and in Babel, you'll get a `ReferenceError`, because `foo(..)` is not an available lexical name inside itself.

**Comment by jesseminn** [comment]
Thank you for helping me!
