### ISSUE TITLE
Closures within loop example

### ISSUE THREAD

**Issue by bpoinder85** [getify/You-Dont-Know-JS#1190]
In chapter 5 of scope and closures you state 

> But, the way scope works, all 5 of those functions, though they are defined separately in each loop iteration, all are closed over the same shared global scope, which has, in fact, only one i in it.

However, when I slightly modify your code, this isn't the case.

    for (var i=1; i<=5; i++) {
      foo( function timer() {
             console.log(i);
           });
    }
    
    function foo(action) {
      action();
    }

This is essentially the same example as the one that doesn't work at the top of that section. The only difference is that instead of using setTimeout, I'm using a simple function that just executes the first argument (in this case, a function).

Yet, this prints out 1,2,3,4,5 just fine instead of 6,6,6,6,6,6. I (thought I did) understand why the example in the book prints all sixes, but I do not understand why my nearly identical code doesn't suffer from the same issue. 

If your statement I quoted above is true, it seems that my code should produce the same erroneous result, but it does not. My guess here is that this has to do with the fact that the setTimeout function executes everything after the for loop is done, which is fine, but if that's true, then I don't really understand the lesson that I'm supposed to get from this example.

**Comment by getify** [comment]
> My guess here is that this has to do with the fact that the setTimeout function executes everything after the for loop is done

Yep, that's exactly the difference.

> if that's true, then I don't really understand the lesson that I'm supposed to get from this example.

In your example, you're not really observing stateful closure at all, in that you're executing the function right away, so it walks up the scope chain to the global `i` immediately and finds whatever its current value is, and prints it out. There's no preservation of each value over time, since it's immediate. Therefore, closure is irrelevant and the difference between one `i` and five separate `i`'s is moot.

For five separate values of (aka `1`, `2`, `3`, `4`, and `5`) to be preserved over time (via closure), rather than accessed *in situ*, each closure needs to be over a different `i`.

**Comment by Krinkle** [comment]
```js
for (var i=1; i<=5; i++) {
  foo( function timer() {
         console.log(i);
       });
}

function foo(action) {
  action();
}
```

@bpoinder85 The example code provided here indeed works as expected in its current form. It prints 1 through 5. However, this code is fragile. It makes use of "closure" without providing the behaviour people expect from a closure.

The purpose of a closure is mainly to do one (or more) of these three things: 1) preserve access to values, 2) allow code to be re-used, 3) allow another piece of the program to control when an action occurs.

The above example, none of these are true. It looks like the loop is allowing `foo` to decide when to call `action`, but this is only true if `foo` calls `action` immediately. As such, it might be better for the loop to perform the logging directly. If function `foo()` is changed to call `action` at a later time, it will print `6`, `6`, `6`, `6`, `6`, instead of `1`, `2`, `3`, `4`, `5`.

Below is a modified version of the program that would work as expected:


```js
function logger(val) {
  console.log(val);
}

// decides what the action should be
for (var i = 1; i <= 5; i++) {
  foo(i, logger);
}

// decides when action should happen
function foo(num, action) {
  action(num); // 1, 2, 3, 4, 5
  setTimeout(function () {
    action(num); // still: 1, 2, 3, 4, 5
  });
}
```

**Comment by anjikinnara** [comment]
I understood the event loop this way. Whenever a javascript engine sees a asynchronous call like settimeout, it starts the timer and continues to execute the next code. When the timer says I am done the callback function will be added to the eventloop. By the time the for loop is done the call backs are not even added to eventloop que. So after the for loop is done engine goes to the que and asks for anything to execute. The eventloop sees a bunch of call backs and try to execute them the closure for these call backs is the function where the for loop is there and the value of I there is the final counter value.
