### ISSUE TITLE
Types & Grammar, Chapter 5, Expression Side Effects: side-effecting expressions require a variable reference

### ISSUE THREAD

**Issue by doubleOrt** [getify/You-Dont-Know-JS#1193]
Types & Grammar, chapter 5: Expression Side Effects

You mention this:
> Would you think ++a++ was legal syntax? If you try it, you'll get a ReferenceError
error, but why? Because side-effecting operators require a variable reference to target
their side effects to.

And a few paragraphs later, you also mention this:
> Another example of a side-effecting operator is delete .

However, when you execute the following example, you don't get an error:
```
delete 10; // evaluates to 'true'  
delete {x: 20}.x; // evaluates to 'true' as well.
```

So, if side-effecting operators require a variable reference, and `delete` is a side-effecting operator, shouldn't it throw an error if it indeed does require a variable reference ? Is this merely a wording mistake ?

I did search for the word "delete" in the issues section, but I didn't find anything that mentioned this.

**Comment by getify** [comment]
I suppose the suggestion in that "Because side-effecting operators require..." sentence is possibly a bit misleading.

Trying to draw strict inferences from this statement, the suggestion is here is that this is why there's a syntax error, and by extension that this requirement, being applied to any operator, would result in a similar error. Clearly, that's not the case, on either count.

1. The syntax error stands alone... it's neither because of, nor not because of, the need for a side-effecting operator to have something (technically called a `Reference` type, as named in the spec) to mutate with its side-effect. It's just a fact of the JS grammar.

2. Moreover, not all operators have that same syntax/grammar restriction, as seen by how `delete` doesn't have it.

3. Lastly, the "requirement" is not uniform... by that I mean, some side-effecting operators will throw an error if not given a `Reference` type, others would not.

So in essence, the strictest reading of what I wrote could be a bit misleading, but I don't think I intended that reading.

I didn't intend "require" to be read as formal "requirement" (as in error causing if not), but more intended like: "obviously they need something to side-effect on, otherwise they have nothing to do". And I definitely didn't mean to suggest that all such operators would have uniformity on errors or syntax peculiarity.

In the case of `delete 10`, it just silently skips over and doesn't throw an error. Arguably, it probably should throw an error, but I suspect for various historical reasons, it doesn't.

**Comment by doubleOrt** [comment]
@getify  Indeed, it was that, I interpreted "require" as "if it isn't there, an error will be thrown", because it is very easy to "infer" that assumption from the preceding statement ("you'll get a reference error, but why ?").  I know that I am reading the books with much more attention that the average reader would give (you could interpret this as negative or positive). 

Anyways, could one say that `10++` throws an error because it is actually interpreted as `10 = 10 + 1` (which will throw a `ReferenceError`) ? The error messages are different, so I don't know.  But if this assumption is true, it would be much clearer if it was mentioned.

What are some other side-effecting operators in JavaScript that throw errors if not used with a variable ?


By the way, I have been fussing about for quite some time without showing my appreciation, so I just want to say that the books are great and the fact that you don't just dismiss most things (the coercion chapter for example) is something I truly appreciate. The books themselves, and the fact that they are open-source, are indeed of the greatest ways that one could serve this community with (I hope I didn't make a grammar error in this sentence, it is quite hard ). Thanks!
