### ISSUE TITLE
Curly braces labeled statements note is not true in chrome

### ISSUE THREAD

**Issue by chiptus** [getify/You-Dont-Know-JS#1212]
First, I'd love to take the chance to thank you for this series of books. I enjoy them very much, and planning to buy the ebooks for my second read into them, so thank you very much.

The *Not True* note in end of this [sections](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch5.md#labels) (last paragraph) is not not true in chrome. Running `{"a":42}` in the console gives me the object {a:42}.

I realize why this should work as you say, but I guess chrome understood that the common case will be to make an object instead of labeled statement.

**Comment by getify** [comment]
A couple of other issues have already touched on this subject: #1081 #1124

As mentioned in those threads, it's a known issue that browser dev consoles are no longer consistent on this topic (changed after publication).

Chrome and Safari at some point started pre-emptively parsing for JSON in the console, but Firefox does not.

**Comment by benjamingr** [comment]
CC @Zirak @paulirish in case you want to explain the changes, rationale and/or PR it.

**Comment by Zirak** [comment]
It's my fault, sort of, you can blame me. My rationale was that as an avid javascripter, I found myself pasting objects into the console quite often, and *it always errored out*.

Even worse, one couldn't just tell a coworker or random internet stranger to write an object into the console because how silly of them to not understand that in a *statement*, they're not *really* writing an object, but rather a block followed by a label, duh-doi. Queue up the "wait javascript has labels?" if they're C programmers, or the exasperated gasp of "oh javascript is so weird".

It was never a good time to teach someone about labels or blocks, because they just wanted to write an object, not hear an hour long lecture about parsers and tokenisers. One had to rely and teach tricks like putting objects in parentheses before writing them in. To me, that seemed silly and worthy of change.

This moment can also be taken to show people the devtools' Snippets feature, which does not alter your input in any fashion.
