### ISSUE TITLE
Async & Performance ch3 confusing about promise error handling swallow

### ISSUE THREAD

**Issue by amanda94** [getify/You-Dont-Know-JS#1220]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).
The book says that 
`The limitations of how Promises are designed -- how they chain, specifically -- creates a very easy pitfall where an error in a Promise chain can be silently ignored accidentally.` Also the `Error Handling` part saying that `catch` deal with errors but when the function in `catch` has error, the error would not be caught.
But I tried with `Promise.reject("oops")` without `catch` ,I got an error consoled both with Chrome and Nodejs 6.12. Also `Promise.reject("opps").catch(e=>{throw e})` got the same result. It seems the error was not  swallowed. 
So I am very confused about the error handing content, such as the suggestion about done(end the chain) usage .What does the error swallowing part means? any examples?

**Comment by getify** [comment]
After the spec was released, and this book was written, the JS engines -- actually, the platforms (browsers, node) around the JS engines -- responded to the problem of it being so easy for rejections to be unhandled. They added, outside of the JS spec, this console notification of unhandled rejections, so that if you made the mistake of not handling the rejection, you'd get told of your mistake.

The console notifications are basically a bandage to cover up the real problem, which is the poor design of the Promise API in this respect. That's what the book text is referring to.

**Comment by amanda94** [comment]
I see.Thanks for reply
