### ISSUE TITLE
The value from the typeof operator

### ISSUE THREAD

**Issue by Mongenet** [getify/You-Dont-Know-JS#1234]
In chapter 2, there is the sentence: "The return value from the typeof operator is always one of six (seven as of ES6! - the "symbol" type) string values." The six given examples are: "undefined", "string", "number", "boolean", "object", "undefined".
I think it is an error because the typeof operator can yield the "function" value, as shown later in the chapter, where function is described as a subtype of "object".
So the return value from the typeof operator is always one of seven (eight as of ES6! - the "symbol" type) string values.

**Comment by getify** [comment]
Quoting you:

> The six given examples are: "undefined", "string", "number", "boolean", "object", "undefined".

Do you see that you repeated "undefined" twice?

For the record, the six return values prior to ES6 are:

* "undefined"
* "object"
* "boolean"
* "number"
* "string"
* "function"

The seventh added to ES6 is "symbol".

The phantom eighth one would be "null", except that the bug in JS is that `null` returns "object".

**Comment by Mongenet** [comment]
Thank you, I didn't see that I repeated "undefined".
I was confused by the example. I saw that "object" appeared twice because of the strange result of typeof null, but didn't see the 2 "undefined" occurrences separated by 4 examples.

**Comment by getify** [comment]
BTW, the reason I didn't include "function" in the code snippet immediately above the sentence in question, is because even though `typeof` returns `"function"`, a `function` is not a proper primitive type according to the JS spec. It's a "sub-type" of object.

Neither the code snippet nor the sentences after it are actually intended to list out all six/seven return values of `typeof`. I specifically didn't want to muddy the waters here with "function is a typeof return but not a type".
