### ISSUE TITLE
Float Subtraction: Unexpected result

### ISSUE THREAD

**Issue by amanshu-kataria** [getify/You-Dont-Know-JS#1246]
1.00000100-0.00000100 results in 0.9999999999999999.

Why does this happen? How to get correct result?

**Comment by getify** [comment]
It happens because of IEEE-754, nothing specific to JS. There's no way to get the math exact, but there is a way (covered in the Types & Grammar book) to use what's called the machine epsilon to check that the number you're comparing to is "close enough" to the number that it's considered within this margin of floating point error.

**Comment by amanshu-kataria** [comment]
@getify Thanks for your response.
