### ISSUE TITLE
Troubled Snippet, Scope & Closures Chapter 4

### ISSUE THREAD

**Issue by Mahdimeraji07** [getify/You-Dont-Know-JS#1257]
The last snippet code in **Scope & Closures, Chapter 4** in [Function First](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch4.md#functions-first) section seems to be incorrect.
It didn't really work because _foo_ is actually undefined, I test that in different environments but maybe I'm wrong but anyway it was confusing for me.

**Comment by getify** [comment]
Are you testing in a console or in a real js program (not node)?

**Comment by Mahdimeraji07** [comment]
Yes, I've tested on standalone Firefox/Chrome console, an HTML file & Node env and I've got the same ReferenceError foo is not a function.

**Comment by itsdanielmatos** [comment]
I was just wondering if there is any update on this issue, I really want to get it clear on my mind.

**Comment by getify** [comment]
IIRC correctly, the spec calls for those to be hoisted, but I think browsers are allowed (in Appendix B) to violate this part of the spec, because of backwards compatibility. The whole issue of "functions in blocks" is confusing to me, because of this compat/breakage issue, and it changed (at least once) since the books were written. It's an open issue to try to re-address this topic in the second edition of the books. But my recommendation is going to be: avoid functions-in-blocks -- it's too murky to be worth it.

**Comment by dragonishare** [comment]
the same issue for me
