### ISSUE TITLE
Typo in chapter 5-Prototypes 

### ISSUE THREAD

**Issue by anuragaravindjoshi** [getify/You-Dont-Know-JS#1264]
There is a typo in chapter 5-Prototypes, section [Setting & Shadowing Properties](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch5.md#setting--shadowing-properties) in the list where shadowing the property is described. In the first point :  ....it's not marked as read-only(writable:false)...
Here writable should be true.

**Comment by getify** [comment]
This is not a typo. Please search already closed issues for explanation.

**Comment by firebase007** [comment]
? .'..,,koo.,@',,,D                                                                                                                                      -2                                                                                                                                                                                                   Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: A,nurag JoshiSent: Friday, 23 March 2018 8:28 AMTo: getify/You-Dont-Know-JSReply To: getify/You-Dont-Know-JSCc: SubscribedSubject: [getify/You-Dont-Know-JS] Typo in chapter 5-Prototypes (#1264)There is a typo in chapter 5-Prototypes, section Setting & Shadowing Properties in the list where shadowing the property is described. In the first point :  ....it's not marked as read-only(writable:false)...
Here writable should be true.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/getify/You-Dont-Know-JS","title":"getify/You-Dont-Know-JS","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/getify/You-Dont-Know-JS"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Typo in chapter 5-Prototypes  (#1264)"}],"action":{"name":"View Issue","url":"https://github.com/getify/You-Dont-Know-JS/issues/1264"}}}
