### ISSUE TITLE
"Appendix C: Lexical-this"- misleading/confusing piece of code?

### ISSUE THREAD

**Issue by Ragzzy-R** [getify/You-Dont-Know-JS#1282]
In the page [Appendix C: Lexical-this](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/apC.md) , the following code explains the issue of `this` losing its binding in the `cool()` function. 

```
var obj = {
	id: "awesome",
	cool: function coolFn() {
		console.log( this.id );
	}
};

var id = "not awesome";

obj.cool(); // awesome

setTimeout( obj.cool, 100 ); // not awesome
```

and it has a workaround below, like this

```
var obj = {
	count: 0,
	cool: function coolFn() {
		var self = this;

		if (self.count < 1) {
			setTimeout( function timer(){
				self.count++;
				console.log( "awesome?" );
			}, 100 );
		}
	}
};

obj.cool(); // awesome?
```

the thing is, the count variable looks like it has something to do with the workaround but it doesn't(or does it?.please correct me if im wrong). It took a while to get my head around why count was used. So can we have a function like the one below for the workaround?

```
var obj = {
	id: 'awesome',
	cool: function coolFn() {
	   var self = this;
           setTimeout( function timer(){
				console.log( self.id);
			}, 100 );
	}
};

obj.cool(); // awesome
```

**Comment by getify** [comment]
These two snippets are not as related as you may be assuming. The second is not intended to be a "hack" or solution to the first. Their patterns are different on purpose. 

The first snippet relies on the 'this.id' to either reference the 'obj' or the global object, to illustrate the problem of 'this' being unpredictable.

The second snippet doesn't use the global object to illustrate, it's focused on another point.

The setTimeout is now inside because that's the only sensible way to illustrate 'self' usage. Also, the 'self.count' is used instead of 'self.id' to reinforce the difference between the first and second snippets.

**Comment by wjkhappy14** [comment]
good

**Comment by wjkhappy14** [comment]
![image](https://user-images.githubusercontent.com/1332924/39767529-95666f5c-5319-11e8-8f3f-ce73827aff60.png)

**Comment by getify** [comment]
Appreciate the feedback. I'll consider reworking some of the wording in second edition.
