### ISSUE TITLE
Types and Grammar, Chapter 4: Coercion - Incorrect Logic

### ISSUE THREAD

**Issue by garrettwgg** [getify/You-Dont-Know-JS#1284]
In the "**Implicitly: * --> Boolean**" section of _Types and Grammar, Chapter 4: Coercion_, this code is presented as evaluating to true, when it in fact evaluates to undefined/false.

```
var a = 42;
var b = "abc";
var c;
var d = null;

[...]
if ((a && d) || c) {
	console.log( "yep" );		// yep
}
```

**Comment by legodude17** [comment]
What do you mean?

**Comment by getify** [comment]
@garrettwgg nope, that section is correct. try the whole snippet in a fresh console session, you'll see. you skipped over an important part in your `[...]`.

**Comment by garrettwgg** [comment]
Ahhh, you're right Kyle. In that case I would suggest that it is possibly a bit confusing. Perhaps it may not be necessary to reassign c to prove your point, or possibly that snippet could be put at the bottom. I was obviously using the values at the top and expecting them to be reused for each example.

**Comment by getify** [comment]
Appreciate the feedback. I think it's important to read all of a code snippet to understand what it does, so I don't want to cater to the idea of skipping parts of snippets and stuff still being predictable.

I could have made the same points by doing separate code snippets, and maybe that would have created less likely confusion. But then it's more verbose, because you have to reset the starting context for each snippet.

I will take some of these things into consideration for the revisions in second edition. Thanks.

**Comment by anurag001** [comment]
@getify Completely agreed! I guess by looking at examples, it seems like different segments and sometimes we take it as a separate one and cause confusion. :)
c has gotten new value "abc" and that's why the whole result will result to true and "yep" will be echoed
if ((a && d) || c) {
	console.log( "yep" );		// yep
}
