### ISSUE TITLE
Clarification about the call and apply instructions

### ISSUE THREAD

**Issue by daformat** [getify/You-Dont-Know-JS#1374]
In this & object prototype - [chapter 2 - Softening Binding](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch2.md#softening-binding)

The following code is given:

```javascript
if (!Function.prototype.softBind) {
	Function.prototype.softBind = function(obj) {
		var fn = this,
			curried = [].slice.call( arguments, 1 ),
			bound = function bound() {
				return fn.apply(
					(!this ||
						(typeof window !== "undefined" &&
							this === window) ||
						(typeof global !== "undefined" &&
							this === global)
					) ? obj : this,
					curried.concat.apply( curried, arguments )
				);
			};
		bound.prototype = Object.create( fn.prototype );
		return bound;
	};
}
```

What I don't understand is `curried = [].slice.call( arguments, 1 )` and later `curried.concat.apply( curried, arguments )`.

I can't help but think that `curried = arguments.slice(1)`and `curried.concat(arguments)` would work just the same. Is there anything I'm missing to understand why you used them the way you did?

Thanks a lot for the clarification and the books.

**Comment by getify** [comment]
`arguments.slice(1)` is not valid, because `arguments` is not an array, it's an "array-like object". The reason for `[].slice.call(arguments...)` is to borrow the generic `slice(..)` method from arrays and apply it against that `arguments` object.

The reason for `curried.concat.apply(curried,arguments)` instead of `curried.concat(arguments)` is similar... `arguments` isn't a real array, so `concat(..)` can't just append its contents to the `curried` array. It could have been written as `[].concat.apply(curried,arguments)`, but in this case, I already had an array (`curried`) to borrow the `concat(..)` function from. I borrowed that method so I could `apply(..)` it, which spreads out a list of values into individual elements.

Consider this code:

```js
function foo() {
   return [1,2,3].concat(arguments);
}
foo(4,5,6);
```

We might hope that would return `[1,2,3,4,5,6]`, but instead it returns `[1,2,3,arguments]`. But if we do:

```js
function foo() {
   return [].concat.apply([1,2,3],arguments);
}
foo(4,5,6);
// [1,2,3,4,5,6]
```

The reason *that* trick works is because the `apply(..)` function doesn't need a real array to spread out its contents as individual elements, and thus `concat(..)` is actually just receiving a call like `[1,2,3].concat(4,5,6)`, which results in the `[1,2,3,4,5,6]` array.

**Comment by daformat** [comment]
Thanks a lot for the fast and detailed answer. I clearly don't know JS :) (as much as I'd like to). Closing the issue.
