### ISSUE TITLE
Adding that sum is the return of the previous function return

### ISSUE THREAD

**Issue by impactcolor** [getify/You-Dont-Know-JS#1413]
In:
.then( function(sum){
	console.log( sum ); // that was easier!

It would be helpful for a newbie to explain that "sum" can be named anything and that it is the return of the previous function return statement.  This logically explains that the then is expecting a return:

// sum here can be named any variable you choose and it will be filled by the return value that just occurred before .then.  
.then( function(sum){
	console.log( sum ); // that was easier!

**Comment by getify** [comment]
Can you cite which book/chapter/section this is in?

**Comment by impactcolor** [comment]
Yes here: https://github.com/getify/You-Dont-Know-JS/blob/master/async%20%26%20performance/ch3.md
Async performance chapter 3 promise value.

**Comment by getify** [comment]
Are you referring to this part?

```js
add( fetchX(), fetchY() )

// we get a promise back for the sum of those
// two numbers.
// now we chain-call `then(..)` to wait for the
// resolution of that returned promise.
.then( function(sum){
	console.log( sum ); // that was easier!
} );
```

Can you clarify why those code comments there are not making it clear that the value (named `sum` here) comes from that promise?

**Comment by impactcolor** [comment]
Yes because it's talking programming lingo.  So to a newbie it's a little confusing...  In example "we chain-call ... to wait for the resolution of that returned promise."  Resolution... promise... what? Considering we're barely learning about promises.  Also function(sum) <- why "sum" does it always have to be sum?   That's why I had suggested this:  // sum here can be named any variable you choose and it will be filled by the return value that just occurred before.  This is just a suggestion of course.  This book is phenomenal and the explanation is great.  But I did  have to think that for a while where was sum coming from?  Did I declare sum somewhere else?

**Comment by getify** [comment]
It seems like there are two issues here, and I want to address them separately.

First, the code comments could have made clear that the callback passed to the `then(..)` receives an argument that is the fulfillment from the previous promise (in this case, the sum of the two numbers).

That detail is explained more later in the chapter, but the code comment could have included it too, like:

```js
add( fetchX(), fetchY() )

// we get a promise back that holds the 
// fulfilled value from the previous promise
// (the sum of those two numbers).
//
// now we chain-call `then(..)` with a callback
// that receives this fulfillment value to the
// parameter named `sum`
.then( function(sum){
	console.log( sum ); // that was easier!
} );
```

That's much more verbose, and I'm not entirely sure it's worth it, but I do concede that the comment could have spelled out the details more, as I just did there.

----

But secondly, to the question about `sum` being able to be named anything, I'm wary of that line of explanation.

Yes, the parameter *could* be called anything... but it **should** be named something sensible, and I really can't think of any other name here than `sum` that more directly explains what its purpose is. Saying "it could be named anything" implies that the name doesn't matter. The JavaScript engine doesn't care, but code is for humans, not the computer, so it does in fact matter.

Moreover, to your question about wondering if you had declared `sum` somewhere else...was the issue that you simply didn't see the `sum` parameter? Or did you see it and not understand what it was creating? I ask because it could perhaps imply a deeper issue in terms of not understanding how parameters create variables in that function scope, or how they receive values when the function in question is invoked.

Those issues are important, but they're not at all the focus of this book. Honestly, this book is the fifth book in a six book series, where generally I am expecting most readers to have read the previous books, and by this point feeling much more comfortable with such details. I wouldn't have put a code snippet that involved in, say, the "Up & Going" book, which is intended for new learners.

What I'm saying is, the fact that this code snippet was confusing to you, if you are a "newbie" as you self identified, is not altogether that surprising. It probably would be a little confusing to most newbies.

Does that all make sense?

**Comment by impactcolor** [comment]
It makes total sense.  Thank you.

**Comment by getify** [comment]
Thanks for the feedback. I will consider it during second edition revisions. :)
