### ISSUE TITLE
Function declaration hoisting

### ISSUE THREAD

**Issue by navdeepio** [getify/You-Dont-Know-JS#1471]
How does the compilation work when a function is hoisted? There's no explanation, just a statement that outlines this behavior

```

foo();

function foo() {
  console.log('hey'):
}

```
Why doesn't it return a TypeError?

**Comment by greengnome** [comment]
It happens because JS interpritator runs 2 times - first time, it will initialize all variables to undefined, and the second time it assigns values to these variables. In the case of "function declaration" interpritator already has this function when it runs the first time.

I tried to explain it as clear as possible :)

**Comment by Davidcreador** [comment]
@navdeepio This is working for me! Not sure what you mean by TypeError! How are you executing it? BTW, you have a typo `:` should be `;`
