### ISSUE TITLE
Gender

### ISSUE THREAD

**Issue by mjdavidson** [getify/You-Dont-Know-JS#1508]
**Please type "I already searched for this issue":** I already searched for this issue

**Edition:** 2nd

**Book Title:** This Object Prototypes

**Chapter:** 4

**Section Title:** Class mechanics

**Problem:** Is it possible to refer to people with a gender-neutral pronoun rather than saying "the architect ... she" or "the builder ... he"

**Comment by krfong916** [comment]
I see the effort that @getify and contributors have made to make their language accessible for women, and I appreciate it. 

I think we can make the experience of this series better for wider audience of people if we use gender inclusive language using pronouns such as they, them, theirs instead of sticking to a binary. It's a subtle change of language, but can make a big difference.

I have no problem doing the work to change the use of pronouns to be more inclusive.

**Comment by getify** [comment]
I appreciate and am sensitive to this topic and I will endeavor to keep it mind as I write the second edition text.
