### ISSUE TITLE
this-object-prototypes/ch5 - wrong output

### ISSUE THREAD

**Issue by m4mum** [getify/You-Dont-Know-JS#1524]
I already searched for this issue,
**Edition:** :2nd (hosted on github)
**Book Title:** : this & Object Prototypes
**Chapter:**:5
**Section Title:** : "Constructors"
**Problem:**

`function NothingSpecial() {
	console.log( "Don't mind me!" );
}

var a = new NothingSpecial();
// "Don't mind me!"

a; // {}`  <-- It should be //NothingSpecial {}

**Comment by getify** [comment]
This is not a mistake. The information you describe is additional metadata that a developer tools console may (or may not) want to share, which is the constructor of an object. What I showed in the comment on that line is that the result of that `new` constructor call is a plain, empty object. I don't, in general, want to get into the game of trying to indicate what developers tools will display for developer convenience, since these things change regularly and since they also vary by developer tool vendor. Thank you.

**Comment by m4mum** [comment]
Thanks for clarifying
