### ISSUE TITLE
this & object prototypes, Setting & Shadowing Properties

### ISSUE THREAD

**Issue by YaroslavTER** [getify/You-Dont-Know-JS#1663]
**Please type "I already searched for this issue":** I already searched for this issue

**Edition:** 1st

**Book Title:** this & object prototypes

**Chapter:** 5

**Section Title:** Setting & Shadowing Properties

**Question:**
In the text mentioned that [[Prototype]] traversed, just like for the [[Get]] operation. 
>If foo is not already present directly on myObject, the [[Prototype]] chain is traversed, just like for the [[Get]] operation.

But doesn't it performs like [[Set]] operation? I just don't get it. Or then why it similar to [[Get]]?

**Comment by getify** [comment]
`[[Set]]` is what it's called now, but back then when the book was written, it was called `[[Put]]`. As the text explains, `[[Put]]` has to traverse the prototype chain like `[[Get]]` does, because of the checks it performs (described in the numbered-bullet list a few paragraphs after the sentence you quoted). A lot of people assume that `[[Put]]` / `[[Set]]` just operate directly on the object, and don't realize that properties/accessors higher up the prototype chain can affect their behavior.
