### ISSUE TITLE
inter-invoked functions acronym (IIF) is used before it is defined

### ISSUE THREAD

**Issue by maxgabut** [getify/You-Dont-Know-JS#1667]
In Appendix A of the second edition of "Scope & Closures", IIF is used to refer to inter-invoked functions.

Unless I missed something, it is first used before it is defined. It might make sense to define it earlier.

The first use is in [Are shynchonous callbacks stille closures]( https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/scope-closures/apA.md#are-synchronous-callbacks-still-closures):

> - **_IIF_** functions don't move around, why would they need closure?

Definition is in [Synchronous callback](https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/scope-closures/apA.md#synchronous-callback):

> Let's refer to (the functions formerly known as) synchronous callbacks, as inter-invoked functions (IIFs).

**Comment by getify** [comment]
You're technically correct, but that bullet point is "hoisted" to the top of that section as sort of preview/table-of-contents... it's not content itself. It's saying, "hey, look out for the following topics to be covered over the next few sections". IOW, it's *good* that you ask "what is an IIF?" when reading that, because that's the point of the table of contents.

I had contemplated expanding that acronym there, but it seems unnecessary since I haven't explained what "inter-invoked function" means yet at that point either, so it's just extra noise.

**Comment by getify** [comment]
Oh... also... there's a very subtle pun intended there, which is signaled by the italics. The sentence is saying "if functions are..." as in a postulated conditional. The pun is that "IIF" is pronounced the same as "if".

**Comment by maxgabut** [comment]
Well yes, expanding the acronym would not help much without a longer explanation (that comes later).

I was a bit confused by it because I confused it with an IIFE (I thought : what's that "IIF" already ? Oh right, the Immediately Invoked Function thingy). But, I guess that's on me :sweat_smile:
