### ISSUE TITLE
"types & grammar": review - vball525

### ISSUE THREAD

**Issue by ghost** [getify/You-Dont-Know-JS#170]
For reference I am testing using JSFiddle with Chrome 36, Firefox 30, and IE 11.

Chapter 1 - Looks real good and all examples worked.
Chapter 2
- Strings Section
  - In the first example "b !== d;" is returning True instead of False as stated. All 3 browsers.
    try
    {
    var a = "foo";
    var b = ["f","o","o"];
    document.write(a.length); document.write(' ');                           // 3
    document.write(b.length); document.write(' ');                           // 3
    document.write(a.indexOf( "o" )); document.write(' ');                   // 1
    document.write(b.indexOf( "o" )); document.write(' ');                   // 1
    var c = a.concat( "bar" );          // "foobar"
    var d = b.concat( ["b","a","r"] );  // ["f","o","o","b","a","r"]
    document.write(c); document.write(' ');
    document.write(d); document.write(' ');
    document.write(a === c); document.write(' ');                            // false
    document.write(b !== d); document.write(' ');                            // false
    document.write(a); document.write(' ');                                  // "foo"
    document.write(b); document.write(' ');                                  // ["f","o","o"]
    }
    catch(ex)
    {
    alert(ex);
    }

**Comment by Pashtunzoy** [comment]
**Chapter 5**

> **Contextual Rules:** 

`It's a very common belief that JSON is a proper subset of JS, so a string of JSON (like {"a":42} -- notice the quotes around the property name as JSON requires!) is thought to be a valid JavaScript program. Not true! Try putting {"a":42} into your JS console, and you'll get an error.`

`That's because statement labels cannot have quotes around them, so "a" is not a valid label, and thus : can't come right after it.`

It gives you an object ` {a: 42}` in the latest version of Chrome, as of the date of this comment. 
It does give you `SyntaxError: missing ; before statement` in the latest Firefox.
