### ISSUE TITLE
Does `module` need quotes?

### ISSUE THREAD

**Issue by liunnn1994** [getify/You-Dont-Know-JS#1849]
**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

----

**Please type "I already searched for this issue":** I already searched for this issue

**Edition:** 2nd

**Book Title:** get-started

**Chapter:** Chapter 2: Surveying JS

**Section Title:** Each File is a Program

**Problem:** Does [`module`](https://github.com/getify/You-Dont-Know-JS/blob/85b2e6c5fa03b95d044015d6e44b72b8beb6a53b/get-started/ch2.md?plain=1#L34) need quotes? 
`<script type=module>` => `<script type="module">`

**Comment by FelipeBarrosCode** [comment]
Yes you need quotes and maybe relative addressing depending on the file that u are referencing.

<script type="modules"> but in case that the module file is in a different folder from the HTML file u can use relative addressing like <script type="../module"> this is to reference to the parent folder for instance where your module file might be in.
This happens because the type is still a HTML attribute.
