### ISSUE TITLE
Numbers coerced to strings when set as object property names

### ISSUE THREAD

**Issue by emadkhan** [getify/You-Dont-Know-JS#1888]
----

**Please type "I already searched for this issue":** I already searched for this issue

**Edition:** 2nd

**Book Title:** Objects & Classes

**Chapter:** Chapter 1

**Section Title:** Property Names

**Question:**

> The 42 property name will be treated as an integer property name (aka, index); the "41" string value will also be treated as such since it looks like an integer.

This is incorrect, or has become incorrect in recent ES2023 compared to when this text was written.

```
> let num = 42;
undefined
> let newObj = {num: false, [num + 1]: true};
undefined
> newObj
{ '43': true, num: false }
> newObj[3.14] = "pi";
'pi'
> newObj
{ '43': true, num: false, '3.14': 'pi' }
> Object.keys(newObj).map((val) => typeof val);
[ 'string', 'string', 'string' ]
```

**Comment by getify** [comment]
TBH, this is a bit of a tricky issue to sort out.

First, the [spec does sort of agree with you](https://tc39.es/ecma262/2024/#sec-object-type):

> The properties of an object are uniquely identified using property keys. A property key is either a String or a Symbol. All Strings and Symbols, including the empty String, are valid as property keys. A property name is a property key that is a String.

However, the *very next paragraph* contradicts this:

> An integer index is a property name n such that CanonicalNumericIndexString(n) returns an integral Number in the inclusive interval from +0𝔽 to 𝔽(2**53 - 1). An array index is an integer index n such that CanonicalNumericIndexString(n) returns an integral Number in the inclusive interval from +0𝔽 to 𝔽(2**32 - 2).

So there absolutely *is spec support* for the idea -- not just my invention! -- that using an integer-looking string as a property name *may* (should) end up being treated numerically. However, the spec seems to only use these "integer indexes" for arrays/typed-arrays and for the special numeric properties of the "exotic" String objects and `arguments` objects... but not explicitly for normal, plain objects.

----

That said, your primary argument (console output quoted above) is fairly shaky. I'm not sure if that's Node but I'm guessing it is, because my Node instance quotes those property names just as your output indicates. But it's important to note that console/debug output is *not* necessarily spec compliant behavior. Consoles in devtools are free to do whatever they think is most helpful/ergonomic for developers, even if it directly contradicts technical spec behavior. There are many such cases. So Node quoting those properties is not a *proof*.

See here screenshots from Chrome and Firefox:

![chrome](https://github.com/user-attachments/assets/767a0134-1b24-4dac-a510-5751e9db2e57)
![firefox](https://github.com/user-attachments/assets/2ad31dfd-ba4d-4c57-961f-896481452e29)

In both those dev consoles, you can see they chose to represent the integer-looking property names **WITHOUT** quotes, opposite of what Node's console does.

Who's right, who's wrong? Well... depends on your perspective.

And BTW, `Object.keys()` (as well as other operations that enumerate properties, such as `for..in` loops, etc) have *always* ensured the normal enumerable, non-symbol keys were represented as strings. In fact, they do so even against exotic String objects, arrays, and `arguments`, all of which the spec definitely indicates are treated as "integer indexed":

```js
var arr = [ 3, 5, 7 ];
Object.keys(arr);   // [ "0", "1", "2" ]

var str = new String("foo");
Object.keys(str);   // [ "0", "1", "2" ]

function foo() {
   console.log(Object.keys(arguments));
}
foo(3,5,7);   // [ "0", "1", "2" ]
```

So the output of `Object.keys()` / etc is not *proof*, either.

----

IMO, it doesn't matter much whether the JS engine coerces all numbers into strings, or coerces all integer-looking strings into integers.

From an observable perspective, all integers and integer-looking strings are treated interchangeably when used as properties/keys. JS makes sure to normalize them to each other, no matter which kind of value you use for the key reference.

IOW, you cannot have separate properties named `"3"` and a `3`, those will always resolve to the same property. Thats the *main reason* I included this discussion in the book is so that developers realize that `arr["3"]` is going to be treated the same as `arr[3]`, and further that this is true whether you're using an array or a plain object.

But which direction the coercion occurs... AFAICT, there's no way to observe or prove that. One engine may choose to do it one way, and another engine may choose to do it the reverse -- just like dev consoles have similar freedom of representation. They're all still compliant if they preserve the expected behaviors.

**Comment by emadkhan** [comment]
Great answer. I agree that exactly what type is being used is opaque to us and all we have to go on is different representations reported by environments such as Node repl (yes that is what I was using, I should have specified) or Dev Tools console.

Great to hear from you, I purchased the two 2nd editions books and am now making my way through Objects & Classes.
