### ISSUE TITLE
"types & grammar": explain Symbol coercion in ch4

### ISSUE THREAD

**Issue by getify** [getify/You-Dont-Know-JS#274]
implicit coercion is an error:

```js
var s = Symbol("not cool");
s + "";  // error
```

explicit coercion is ok:

```js
var s = Symbol("cool");
String(s);  // "Symbol(cool)"
```

**Comment by css-nerd** [comment]
Interesting. Not sure, whether this is a bug. It might have originally been an intentional decision, when taking into account that Symbols supposed to be used as unique values. 

The explicit coercion does not actually change the value, but implicit coercion might (e.g. `s + "bla"`). Maybe this was done to prevent duplicates?

**Comment by getify** [comment]
Pretty sure this is intentional. Reasoning:

[`ToNumber` 7.1.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-tonumber):

> Symbol 	Throw a TypeError exception.

[ `ToString` 7.1.12](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-tostring)

> Symbol 	Throw a TypeError exception.

Strangely, `ToBoolean` just makes it `true` instead of an error.

But anyway, in all the places where an implicit coercion would happen, it would end up going to `string` or `number`, so in both those cases an error is produced.

That leaves one last question: how does `String( symb )` not throw the error by invoking `ToString`? They invented an exception! (groan)

[ `String(..)` 21.1.1.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-string-constructor-string-value)

> Else,
> * If initializing is false and Type(value) is Symbol, then return SymbolDescriptiveString(value).
> * Let s be ToString(value).

**Comment by anba** [comment]
FYI: https://esdiscuss.org/topic/string-symbol for background info.

**Comment by css-nerd** [comment]
With this in mind, Symbols seem to be the strangest data type in ES6, so far.

I thought this was a bug, since FF36 and recent Chrome versions are the only decent brosers that currently support Symbols: http://kangax.github.io/compat-table/es6/

**Comment by getify** [comment]
@anba thanks for the link. dunno why they're so set on throwing for `sym+""` but whatever.

**Comment by getify** [comment]
I would've preferred overloading `+` to create a new symbol to avoid this supposed pitfall:

```js
var s1 = Symbol("foo");
var s2 = s1 + "_bar";

String(s2); // Symbol(foo_bar)
```

but what do i know? :)

**Comment by ljharb** [comment]
- throws can always be removed, so in general it's far better for the spec to have a strange thrown exception that can later be removed (like `new RegExp(/a/g, 'i')`) than to have behavior that can never be undone or removed.
 - explicit coercion via + is always horrible because it invokes `valueOf`, not `toString`. `String(x)` is always the proper way to coerce to a string.
 - The footgun here is `obj[Symbol('foo') + 'bar']` imo, which could happen indirectly via vars. your suggestion of making a new Symbol is a pretty good way to avoid this, imo - but that can be added at any time, because of the throwing behavior.

**Comment by getify** [comment]
"explicit coercion via + is..." surely you meant to call that "implicit coercion", right?

> String(x) is always the proper way to coerce to a string.

I agree, but /be says +"" is the better string coercion. So, clearly, there's just no rational way forward.

**Comment by getify** [comment]
> throws can always be removed

Actually, I'd bet quite a bit of money that some lib is going to rely on the throw for some detection or guard... there's no way to reliably know for sure that some shit we add in now won't become permanent. The rule should be "whatever shit we add in now will become permanent".

"There's nothing more permanent than a temporary hack."

**Comment by ljharb** [comment]
Yes, I did mean implicit, sorry.

where does brendan say that about string coercion?

TC39 has always been ok with removing exceptions - if someone relies on an exception and it stops being thrown, that's not something they'll worry about.

**Comment by getify** [comment]
> when does brendan say that about string coecion?

here: https://esdiscuss.org/topic/string-symbol#content-11

"Use +'' if you want ToString in the language, I say."

He further asserts that ASM.js implies these are "explicit" coercions: https://esdiscuss.org/topic/string-symbol#content-15
