### ISSUE TITLE
Up and Running

### ISSUE THREAD

**Issue by shelleyp** [getify/You-Dont-Know-JS#309]
Just wanted to note your writing is very readable, preface is excellent, and you provide a clean view of JavaScript. Definitely going to be a book I recommend in the future.

**Comment by pertrai1** [comment]
Hey @shelleyp, if you have bought any of the books it would be great to write a review on the site where you bought the book.

**Comment by shelleyp** [comment]
I'm a tech reviewer.

**Comment by getify** [comment]
<3 @shelleyp

**Comment by mallowigi** [comment]
This is indeed a very readable book; in fact, having read a lot of books about Javascript (The Good Parts, Eloquent Javascript, Javascript Allonge) this is the one that enlightened me the most, but only because I'm an advanced developer already (this book made me go up from "Advanced" to "Expert" as I've been able to understand promises, closures, the "this" keyword and Object prototype functions).

I've recommended it and definitely recommend it again.

**Comment by getify** [comment]
Thanks, all! :)
