### ISSUE TITLE
"up & going": Editorial comments

### ISSUE THREAD

**Issue by bmacdonald-oreilly** [getify/You-Dont-Know-JS#312]
Editorial comments for "Up & Going"

Chapter 1
-------------
There are going to be a lot of new terms in this chapter. You may want to introduce new terms in italics; that’s standard ORA format.

Section “Code”:
First example: Mention that JavaScript is abbreviated JS.
Define the term “syntax.”
Mention that the * means multiplication. A whole section on operators is probably needed, but you can ignore that for the first example.

This sentence: “What about "executing a program"? A special program on your computer is responsible for reading your "program" from the text file and turning it into commands that your computer can recognize.”
You’re using “program” to refer to two different things here; that’ll confuse readers. I suggest:
“What about “executing a program”? The program you write (a text file) is passed to a different special program called the compiler, which reads the text file and turns it into commands that the computer can recognize, called an executable, which usually isn't human-readable.”

This sentence: “Other languages are designed to be "compiled" while being run, or interpreted,”
You’ve equated run-time compilation with interpretation here. But in the next sentence, you say this: “JavaScript is of the latter type: it is compiled (not interpreted!) during its execution”
This seems contradictory. Is run-time compilation considered interpretation or not?

Mention that “executing” a program means running it.

Section “Try It Yourself”:
For complete beginners, you’ll need to explain what the developer tools console is — you’ve told users they’re writing in a text file up to this point, so they may be expecting NotePad or TextEdit. They’re probably not even aware their browser has developer tools. You should probably tell them where to find it in various browsers.

When they open the developer console for the first time, they’re going to see a bunch of stuff they don’t recognize, and can ignore. They also may not be aware of where to start typing, or how to run the program.

You should explain what the semicolon is for somewhere in here.

Section “Values & Types”
You give an example of values, but you don’t specifically define them — what are they for? Why should the new programmer care?
I would introduce the idea of types, and define the term, before you start using the names of specific types (number, string, boolean). 
You’ll need to define what you mean by primitive values; it’s not clear from the text.
In the examples, you’ll need to explain why the strings are in quotes. 
When you’re talking about built-in types, you should explain what that means — that there are certain operations that are defined for certain types. That is, you can do math with a number, but not a string.
You may want to acknowledge that the use for the Boolean type isn’t obvious at this point, but will become clear later on. 

Section “Converting Between Types” 
You’re using the equality operator without explaining what it does, or why there are two equals signs. You should also explain Booleans and what they’re for before getting into Boolean values.

General comment: There’s no section on operators. I would have expected that to come after the section on types. This section should include the assignment operator, equality operators, and mathematical operators.

Section “Code Comments”
If you’re going to mention putting a comment on the same line as code, you should give an example of it.

Section “Variables”
You mention “declaring a variable” without explaining what that means. You might want to go into a bit more detail about the assignment operator, if you haven’t done so earlier in the chapter as a result of suggestions.

You’re using console.log() here without explaining what it means.

Should probably go into a bit more detail as to what “state” means.

Something like “amount = amount * 2” is going to be arcane to a beginner. How can you assign something to itself? This requires more explanation.

You’re using the toFixed() method without explaining what methods are. New readers will be confused by the syntax.

Section “Conditionals”
You’ll need to discuss the comparison operators before this will make sense to the reader.

You’ll need to explain in more detail the syntax regarding the brackets and the else statement. 

You should provide a bit more detail about “truthiness” — at the moment, the reader could conclude that there’s a list of secret values that coerce to true, and he doesn’t know what they are. Essentially you need to tell them specifically what coerces to false, and if it doesn’t coerce to false, then it coerces to true.

Section “Loops”
If you’ve explained how the braces work in the previous section, these examples will be more clear. If not, they’ll be arcane.

You might also want to offer a synonym for “iteration”; that’s not a standard term for most people. 

I’d suggest just going a bit slower. Something like: “In a while loop, the keyword while indicates that the following structure is a loop. First the conditional is tested: Are there any customers waiting (numOfCustomers > 0). If the conditional is true, then the code between the brackets is run once, called an “iteration.” Presumably the code inside the loop will reduce the value of numOfCustomers by one. After that first iteration, the condition is tested again. If the condition is still true, another iteration of the loop will be run, and so on, until the condition is false (there are no customers waiting in line).”

Should probably mention that programmers start counting at zero.

Your mention of i++ could be moved to an operators section, if you choose to add one.

Section “Functions”
This paragraph: “A function is generally a named section of code which can be "called" by name, and the code inside it will be run each time. Functions can optionally take arguments (aka parameters) -- values you pass in. And they can also optionally return a value back.”

This is a lot of information very fast, that beginners will find difficult to follow. You could break this apart to demonstrate called functions, return values, and parameters. Giving an example of each would help make the syntax clearer.

Section "Scope"
“just like if a clown at a birthday party blows up one balloon inside another balloon”
I think this is now my favorite technical metaphor.

Chapter 2
-------------

I’m a little fuzzy on the goal for this chapter. It seemed that Chapter 1 was aimed at “I’ve never programmed before,” and Chapter 2 is initially aimed at “I’ve programmed before, but not in JavaScript.” The first half seems to follow that pattern, talking about values and types, and variables, which differ from C-style languages, so that makes sense. But then it seems like you’re hitting the various topics that are covered in the series: scope, closure, this, prototypes, polyfilling. I thought that the “tour of the series” was covered in Chapter 3. Is it coincidental that the content lines up like that, or did this Chapter wander away from its original purpose?

Intro section:
You should probably define what ES6 means here (and ES5 and ES7, if you like). You mentioned it in Chapter 1, but a beginning JS developer really needs to know what it means.

Section “Values and Types”
You mention setting properties on an object, and you explain how to access them, but the concept of properties isn’t really defined.

Should mention the use of quotes around the property name when using bracket notation.

I suggest you add subheadings for the discussions of arrays and functions.

Probably wouldn’t hurt to note that array indexes start at 0. I know most languages have zero-based arrays, but some don’t.

Chapter 3
-------------
Nothing to add here; I've read most of these books already, and you've done a good job pointing out the high points of each.

**Comment by getify** [comment]
A big chunk of these editorial comments have, at least to an extent, been addressed by my last several commits. Major highlights:

* the intro to Chapter 1 has been reworked significantly, to try to clarify who the audience really is intended to be, and what the expectations for the chapters and the book as a whole should be
* there's an explicit "Output" section (which describes `console.log(..)`, including a brief description of the idea that `log()` is a property/method on `console` -- which also lays the groundwork for `amount.toFixed(..)` later)
* there's an "Operators" section now
* I removed the entire "Closures" section from Chapter 1 and combined it with the "Function Closures" section in Chapter 2.

**Comment by getify** [comment]
> I’m a little fuzzy on the goal for this chapter.

Let me try to articulate my goal for the book (and each of its chapters), because I seem to not be doing well with that so far.

I want the YDKJS books to apply to every level of JS developer, from newbie to advanced. One criticism I got from many readers, prior to attempting this *"Up & Going"* title, was that the books jump right into the deep end and assume at decent basic understanding of JS and programming, something that not all readers had, so they were lost.

So I figured instead of just "losing" those readers, I could provide a bridge from zero to *"Scope & Closures"*, a preamble or prequel if you will. It's the backstory.

This book tries to fill as much of the gap between "little to no programming experience" and "ready for Scope & Closures" as possible, while maintaining a quick and brief overview rather than an intimidating exhaustive reference manual for all bits of teaching "beginning programming".

My intent is that a reader would see this book as a guide of what things should be learned, with enough details to make those explorations concrete and productive, but not necessarily hand-holding through every single detail of that learning. *"Up & Going"* not only introduces you to what you start trying to learn and experiment with to become a programmer, but it augments your learning as you pursue **other beginner programmer** resources.

It's the "Cliff's Notes" for intro to programming.

-------

Internally, the structure is this: 3 chapters (whose titles are very intentional to the intent), 3 layers, like 3 sheets of transparency, which are designed to sit on top of each other. Each layer fills in its own part of the picture. Each layer is useful in its own right, but the way they combine when taken on top of each other is an additional narrative, and indeed the most important reason for this book. Moreover, these chapters forming the book makes the book itself a transparent layer to view on top of the other YDKJS books in the series.

Chapter 1 tries to make you aware of the foundations of programming that you'll need to survive and thrive for the rest of the book, and indeed the rest of the series. It helps you learn, while suggesting strongly that depending on just how little your experience is, you may need to repeat read Chapter 1 many times, and spend a lot of time on its examples "trying them yourself" and doing the "practice", and indeed may need to consult other "beginner programming" resources, too. Only once you feel comfortable with these topics should you move on to Chapter 2. You won't **LEARN ALL OF BASIC PROGRAMMING** with this chapter, but you will be well "into programming" by that point, and that's enough to build on.

Chapter 2 comes back and looks at many of Chapter 1's programming topics, but through an even more JS-specific lens. Again, its goal is to introduce you to the topic more completely than Chapter 1 did (if at all), so that you have enough of a footing that the topic will make sense when its explored in later books of the series. There are several topics which are introduces here which were not appropriate in Chapter 1, like closure, prototypes, etc. But we cover them in a basic enough sense that you're ready for those respective books in the series. You won't **LEARN ALL OF JAVASCRIPT** with this chapter, but you will be well "into javascript" by the point you finish this chapter with confidence, and you'll be good and ready to dig your teeth into the rest of the YDKJS series without them intimidating you.

Chapter 3 finally acts as a roadmap of where to go looking for further coverage of topics in the rest of the books. It's the more detailed version of all the "See ___ of the ____ title" notes that are strewn throughout Chapters 1 and 2. It sets expectations for what the books are about, and gives you a proper mindset for how to approach each book, and perhaps even a sense of which book or books you should tackle next (not necessarily chronologically, depending on your current experience).

------

The arc of a topic from this book through its three chapters and into the specific chapter/book in the proper part of the series tells a complete story, but you come at this topic several times, each time more in-depth than before, more detailed, more rigorous. By the end, you've come from "nothing" to "completeness" in terms of exploration. But you can't do that all in one sitting. So there's Chapter 1's coverage, then it's revisited in Chapter 2, then it's mentioned in Chapter 3 to show the context that it fits into a wider book in the series, THEN finally you go to that book in the series and the topic is fully explored.

For example, the coverage of types/coercion. Chapter 1 explains this idea at a 50,000 ft view. Chapter 2 explains the topic in a more JS specific way, at the 5,000 ft view. Chapter 3 points you to the *"Types & Grammar"* book with specific narrative about the controversies around coercion, and motivates why you should go dig into that book and Chapter 4.

So, mentally, if you follow coercion through the chapters of *"Up & Going"* and then Chapter 4 of *"Types & Grammar"*, by the end we've layered on all the different bits you need to go from zero knowledge of it to full confidence in it.

If the first time you read about anything coercion related was **just** Chapter 4 of T&G, you might very well be overwhelmed. But U&G gets you "up & going" with the topic so you're ready.

+@simonstl

**Comment by bmacdonald-oreilly** [comment]
With regard to the new intro, I would emphasize more strongly the idea that this book itself is not a substitute for a good intro-level book or course, if you have no experience at all. 

The Input/Output and Operators sections look good. You might want just a touch more information, even if it's "we'll explain this more later," on the dot operator (because readers don't know what objects are), and the AND/OR operators (same thing, re: Boolean logic).

**Comment by getify** [comment]
just posted a bunch of extra tweaks/updates, addressing the rest of these editorial comments.

**Comment by getify** [comment]
closing for now. feel free to re-open if there's more feedback to provide.
