### ISSUE TITLE
JavaScript internals

### ISSUE THREAD

**Issue by mohanr** [getify/You-Dont-Know-JS#316]
I code AngularJS but not a JS expert. So these questions may not make sense. 
1. How do I know more about the engine or VM that executes JS ?
2. Is there something like Java's GC ? What are the algorithms ?
3. Is there a library like Doug Lea's java.util.concurrent ? What are the concurrency issues ?
4. Is there a memory model like the JMM ?

Are there references to these internal details ?

**Comment by benjamingr** [comment]
Did you see the async and performance book? It should cover your concurrency and performance issues: https://github.com/getify/You-Dont-Know-JS/tree/master/async%20%26%20performance 

As for engine internals since there are several engines it's hard to cover generally but there is a lot on material online about v8 for example - the problem is it might become irrelevant tomorrow if they change algorithm - the ES specification does not make any guarantees about the memory model and engines are free to implement them as they see fit (outside of typed arrays and the such). 

Same goes for GC, it is engine independent.

**Comment by getify** [comment]
+1 @benjamingr except `s/engine independent/engine dependent/` :)

**Comment by benjamingr** [comment]
Thanks for the catch :)
