### ISSUE TITLE
Microbenchmarking harness

### ISSUE THREAD

**Issue by mohanr** [getify/You-Dont-Know-JS#322]
Do the types of issues considered by Alex Shipilev's JMH(Java Microbenchmarking harness) apply to JS ? One link is http://shipilev.net/talks/devoxx-Nov2013-benchmarking.pdf

What serious tools are used by the JS developers to micro benchmark ?

**Comment by RReverser** [comment]
Take a look at [Benchmark.js](http://benchmarkjs.com/) - it's used behind the JSPerf and already contains a lot of tricks to prevent unwanted optimization between cycles.

**Comment by mraleph** [comment]
@mohanr yes, they do apply. I have been [talking](http://mrale.ph/talks/lxjs2013/#/) about it for a while now. 

Sadly there is no tool comparable in sophistication to JMH. Prime reason for that, I think, is the diversity of JS engines - when you try to pick up a blackhole implementation you always have to think how it will behave on different VMs, will it be fast enough on all of them (not to hide the cost of a microop?), will it work as a _blackhole_ on all of them or will be still optimized away on some of them?

Benchmark.js does almost nothing to prevent optimizations and in a interesting design twist it also reports a mixture of pre-warmup and post-warmup performance which is not always suitable for microbenchmarking. Still it's the best tool there is for macrobenchmarking. 

I would also argue that desire to microbenchmark is often misguided. But that's a completely different story.

**Comment by benjamingr** [comment]
@mraleph first of all thanks for that talk (I've already seen it before). 

The problem lies IMO in the fact that there are a lot of things people naively _expect_ to be fast but are not (either because the optimization wasn't written, because there are spec related constraints, or because they don't understand an operation deeply).

To take a simple example - the fact `delete` causes a deopt to hash maps and that setting an object's prototype to an object converts it to a hidden class. These things of course make sense because the engine makes assumptions on how people use these language features: deletion means an object is being used as a map and that setting a prototype means the methods will be accessed a lot and changed only a little. However, these assumptions don't always hold.

Add that to the fact that like you said microbenchmarks are hard and often misguided you get a lot of people who need to write faster code (yes, there are plenty of times it's an actual requirement) and resort to voodoo and cargo cult programming. (like never using `delete` even in times the heuristic actually helps them by giving them a more fitting representation as a map, implementing constant propagation as a build step, caching `length` in loops when it's not needed and so on).

Now you're educating people on these subjects and how things actually work is both awesome and helps mitigate the problem but your posts are hard and time consuming for the average JS developer who still needs to write fast code sometimes that calculates things - having better benchmarking tooling combined something like IRHydra that also explains (yes, I get that's v8 specific) in every day language performance would be really helpful.

What I'm saying here is that __a tool that also lets you know why your benchmarks might be bad would be immensely useful__. Something that looks like JSPerf but also lets you know what your code turns into (yes, in the specific case of v8 when it is run) and what possible pitfalls you're missing here (like constant propagation,  DCE and so on) would help those vast majority of developers who don't really grok v8 or VMs in general but still care about performance sometimes.

(By the way: Petka started writing a tool that uses every day language to let people know about deopts https://github.com/petkaantonov/nodeperf but it seems abandoned)
