### ISSUE TITLE
Memory footprint

### ISSUE THREAD

**Issue by mohanr** [getify/You-Dont-Know-JS#330]
I am wondering what type of footprint is tracked in a browser engine. In the case of Java we have our JVM memory footprint. Real-time graphs can be seen using JMX.

I know that our AngularJS footprint is large. How should we measure it ?

**Comment by benjamingr** [comment]
Well, the easy answer is `performance.memory` but the real answer is harder
since JS runs on several different VMs and each has a different way to
store objects and deal with memory.

There are numerous tools that let you profile and behcmark your JavaScript
code - here is the Chrome official guide for instance
https://developer.chrome.com/devtools/docs/cpu-profiling similar tooling
exists for other browsers as well.
