### ISSUE TITLE
"up & going":"chapter 1: into programming" equivalent for & while loops

### ISSUE THREAD

**Issue by pdawyndt** [getify/You-Dont-Know-JS#357]
Why on earth is the `for`-loop variant that outputs the values from 0 up to and including 9
```js
for (var i = 0; i <= 9; i = i + 1) {
    console.log( i );
}
// 0 1 2 3 4 5 6 7 8 9
```
re-written as a `while`-loop variant that produces the same output in the following way
```js
var i = 0;

// a `while..true` loop would run forever, right?
while (true) {
    // keep the loop going?
    if (i <= 9) {
        console.log( i );
        i = i + 1;
    }
    // time to stop the loop!
    else {
        break;
    }
}
// 0 1 2 3 4 5 6 7 8 9
```
if the it has a more straighforward equivalent 
```js
var i = 0;
while (i <= 9) {
    console.log( i );
    i = i + 1;
}
// 0 1 2 3 4 5 6 7 8 9
```
OK, this one doesn't introduce the usage of `break` (which should be avoided in this case anyway), but the more difficult code seems to distract from the fact that here the point you want to address is that `for`-loops in some cases are a more succinct replacement for `while`-loops, and that this is the case when the number of iterations is known beforehand (at the point when the `for`-loop is initiated).

**Comment by getify** [comment]
The reason is entirely intentional.

I'm teaching the concept of a loop as "keep doing some task until this XYZ thing is no longer true, and then stop." The loop forms where the condition test clause is in the header, like `while (i <= 9)`, obscures the fact that there's an `if`-statement happening each loop which is checking that condition, and if it fails, it's *break*ing out of the loop. So I'm explicitly illustrating that.

I follow up immediately after teaching the underlying concept of the loop with endorsing the shorter forms as being much easier to write. But I want them to explicitly understand the concept rather than just the common syntax.
