### ISSUE TITLE
Is this really correct and why?

### ISSUE THREAD

**Issue by furier** [getify/You-Dont-Know-JS#376]
https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20&%20closures/ch3.md#garbage-collection

    function process(data) {
        // do something interesting
    }

    var someReallyBigData = { .. };

    process( someReallyBigData );

    var btn = document.getElementById( "my_button" );

    btn.addEventListener( "click", function click(evt){
        console.log("button clicked");
    }, /*capturingPhase=*/false );

> The click function click handler callback doesn't need the someReallyBigData variable at all. That means, theoretically, after process(..) runs, the big memory-heavy data structure could be garbage collected. However, it's quite likely (though implementation dependent) that the JS engine will still have to keep the structure around, since the click function has a closure over the entire scope.

What keeps the garbage collector from collecting `someReallyBigData` as `click` has no reference to it even tho its part of `click`'s closure? (assuming it's not part of the global scope)

**Comment by getify** [comment]
Consider what would happen if the click handler in question had an eval(..) in it... then of course JS would have to assume the possibility that you might need to access `someReallyBigData` from inside `btn`. Or, consider the possibility that a reference could dynamically be made to `obj["someReallyBigData"]` and the `obj` could be an alias to `window`, and the scope implied here is in fact the global scope... then of course it'd need to keep the closure around.

The point I was making in the chapter is that it's implementation dependent whether the engine is smart enough to know for sure, in all possible ways, that `someReallyBigData` is definitely no longer needed, because of course it wouldn't be tolerable for it to ever possibly GC it when it was still going to be used. 

Since it depends on implementations and on nuances of situations, I argue the best mindset is to assume closure over an entire scope rather than closure over independent variables in a scope.

**Comment by furier** [comment]
Thank you for clarifying that! Good job on the books!

**Comment by getify** [comment]
Cheers! :)
