### ISSUE TITLE
"async & performance": interleaving example

### ISSUE THREAD

**Issue by babygau** [getify/You-Dont-Know-JS#385]
hi @getify,

i'm a bit lost at this example of interleaving in `generators`

```javascript
var a = 1;
var b = 2;

function* foo() {
  a++;
  yield;
  b = b * a;
  a = (yield b) + 3;
}

function* bar() {
  b --;
  yield;
  a = (yield 8) + b;
  b = a * (yield 2);
}

// an utility that controls an iterator
function step(gen) {
  var it = gen();
  var last;
  return function() {
    // whatever is ` yield` ed out, j ust
    // send it right back in the next time!
    last = it.next(last).value;
  };
}

// make sure to reset ` a` and ` b`
a = 1;
b = 2;
var s1 = step(foo);
var s2 = step(bar);

// run `*foo()` and `*bar()` randomly
s2(); // b-- ;
s2(); // yield 8
s1(); // a++;
s2(); // a = 8 + b;
// yield 2
s1(); // b = b * a;
// yield b
s1(); // a = b + 3;
s2(); // b = a * 2;
console.log(a, b); // => 12 18
```
what i'm wondering is the state of `b` in the last calling step

```js
s1(); // a = b + 3;
s2(); // b = a * 2;
```
i know the correct result is `a = 12` and `b = 18` *(test the snippet with iojs)*. but what confused me is `a = 12` in `s1()`, why `a=9` in `s2()`??? isn't that `a` and `b` are *shared variables* between `*foo()` and `*bar()`? i thought `b = a * 2  = 12 * 2 = 24`. 

here is how i reproduce my incorrect result:
```js
s2(); // yield undefined; b = 1; 
s2(); // yield 8; 
s1(); // a = 2; yield undefined;
s2(); // a = 8 + 1 = 9; b = 1; yield 2
s1(); // b = 1 * 9 = 9; a = 9; yield 9 
s1(); // a = 9 + 3 = 12; yield undefined <~~ OK UP TO THIS STEP!!!
s2(); // b = 12 * 2 = 24; yield undefined <~~ CONFUSION????
```

**Comment by getify** [comment]
Ahh, this is a super subtle gotcha that even I didn't fully realize until now. Hmm... should figure out how to explain this detail in the book in a second edition.

The line `b = a * (yield 2);` evaluates `a` first (moving LTR), which at that moment is still `9`, then pauses. Then you run `s1()` which updates `a` to `12`. Then you run `s2()` again, which sends the previously yielded `2` back in, to be multiplied with the waiting `9`.

The comment `// b = a * 2;` is, in this respect, a little misleading, because it implies you run the whole statement at that point, when in reality the statement was already in progress from the previous `yield` point.

In essence, this is kind of exactly the point I'm making about concurrency and how it's approximating the kind of interleaving that could happen in a truly threaded environment. You *can* do this with ES6 generators, and you can be successful at it just like threaded programs are. You don't need the complexity of mutexes to block pre-emptive threading, since this is cooperative concurrency... You just have to be really careful about the sequencing to avoid pitfalls.

I didn't really intend to make the point about the LTR processing of the expression even being a gotcha in terms of state; I just accidentally did so. But now that I realize it, I should explicitly explain it for second edition. Thanks for pointing it out!

**Comment by babygau** [comment]
many thanks @getify 

> The line b = a * (yield 2); evaluates a first (moving LTR), which at that moment is still 9, then pauses. Then you run s1() which updates a to 12. Then you run s2() again, which sends the previously yielded 2 back in, to be multiplied with the waiting 9.

> The comment // b = a * 2; is, in this respect, a little misleading, because it implies you run the whole statement at that point, when in reality the statement was already in progress from the previous yield point.

This is exactly what I want, all clear now.

Apart from `Javascript: The Definitive Guide`, your book series are second to none :star2:

**Comment by getify** [comment]
Thanks, super honored to have you say that. :)

**Comment by dima716** [comment]
Hi, @getify !
I's going to open an issue about this too but there's one already :)
There's just one interesting thing that If you run this code through [babeljs.io](https://goo.gl/FQsj9Q) the end result is "12 24"

![babbel](https://cloud.githubusercontent.com/assets/8137279/8157324/a052e1e8-135c-11e5-8290-855fcd1c504a.png)

**Comment by getify** [comment]
@dima716

Looks like a bug in [regenerator](https://github.com/facebook/regenerator) (the generator transpiler that babel uses). I've created a [minimal reproduce test case](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&playground=false&code=var%20a%20%3D%201%3B%0Avar%20b%20%3D%202%3B%0A%0Afunction%20*foo()%20%7B%0A%20%20b%20%3D%20a%20*%20(yield%202)%0A%7D%0A%0Avar%20it%20%3D%20foo()%3B%0A%0Ait.next()%3B%0Aa%20%3D%203%3B%20%0Ait.next(5)%3B%0A%0Aconsole.log(a%2Cb)%3B%0A).

Chrome and FF agree, babel (regenerator) is off:

![screen shot 2015-06-15 at 8 43 52 am](https://cloud.githubusercontent.com/assets/150330/8161610/e793d46e-133d-11e5-84e4-31c1ef23ed9e.png)

I've [filed this bug](https://github.com/facebook/regenerator/issues/206) with regenerator. Thanks for finding!
