### ISSUE TITLE
"async & performance": `runAll()` utility solution

### ISSUE THREAD

**Issue by babygau** [getify/You-Dont-Know-JS#394]
hi @getify,

as an attempt of getting an insight into generator concurrency. i'm trying to figure out how to write a "workable" `runAll()` utility as you mentioned in your book.

from my understanding, you used `yield;` in order to hand control to other `generator`. but i couldn't figure out how to let them communicate based on `run(..)` utility (in *Chapter 4: Generator+Promise*). Because `run(..)` will **only advance promise-aware steps inside the generator**, so i removed `yield;` inside the generator and use `Promise.all([..])` as the following snippet (*frankly, untested!*) below. needless to say, i don't feel happy at all bcoz it doesn't satisfy your requirement. your help would be appreciated so much in this matter.

```javascript
var res = [];

runAll(
  function*() {
    var p1 = request('http://some.url.1');

    // no `yield` for control transfer here!!!

    res.push(yield p1);
  },
  function*() {
    var p2 = request('http://some.url.2');

    // no `yield` for control transfer here!!!

    res.push(yield p2);
  }
);

function runAll(gens) {
  var its = gens.map(function(gen) {
    return gen();
  });
  var promises = its.map(function(it) {
    return it.next().value
  });

  // return promise in order
  return Promise.all(promises)
    .then(function(values) {

      var data = [];

      for (let i = 0; i < values.length; i++) {
        Promise.resolve()
          .then(function handleNext(values[i]) {

            // run to next yield
            let next = its[i].next(values[i]);

            // start iterator recursive loop
            (function handleResult(next) {
              // generator has completed running?
              if (next.done) {
                data.push(next.value);
              }
              // otherwise keep going
              else {
                return Promise.resolve(next.value)
                  .then(
                    handleNext,
                    function handleErr(err) {
                      return Promise.resolve(its[i].throw(err))
                        .then(handleResult);
                    }
                  );
              }
            })(next);
          });
      }
      return data;
    })
};
```

btw, i really enjoy reading your book, page 168...paused...waiting for your help to resolve...resume... :triumph:

**Comment by getify** [comment]
`runAll(..)` is quite non-trivial... that's why I omitted it from the book. I don't have a `runAll(..)` that I can dump here (would have to invent one, just as you've attempted)... but I can point you to the [`runner(..)`](https://github.com/getify/asynquence/blob/master/contrib/plugin.runner.js) in my [asynquence](https://github.com/getify/asynquence) lib. Of course, it's doing more than just the `runAll(..)` I suggest in the post, but perhaps studying that code may suggest some things that will help you.

Ultimately, my recommendation is not for folks to invent their own utilities of this complexity, but rather to use existing tools. I understand your desire to do so for learning purposes, and of course that's admirable. If I get some time to circle back here and try to work on a `runAll(..)` that fits with the book's suggested pattern, I will.

**Comment by babygau** [comment]
tks @getify, i totally understand that you have more important work need to be done other than completing `runAll()` so just come back here when you have downtime and ready to work on it (it could be a suggestion for your 2nd edition book, maybe :wink:). your reference is definitely complicated but your example of [using runner to do async csq-style generator coroutine](https://gist.github.com/getify/10172207) is great :100: 

feel free to close this issue when you want it to be!!!
