### ISSUE TITLE
es6: ch2: "const declarations", clarifying optimizations

### ISSUE THREAD

**Issue by chrisdickinson** [getify/You-Dont-Know-JS#438]
From [the text](https://github.com/getify/You-Dont-Know-JS/blob/e49c289219dd88e9552c9c3de0c3174af6e38554/es6%20%26%20beyond/ch2.md#const-declarations):

> There's some rumored assumptions that a const likely will be more optimizable for the JS engine than a let or var would be, since the engine knows the variable will never change so it can eliminate some possible tracking.
> Whether that is the case or just our own fantasies and intuitions, the much more important decision to make is if you intend constant behavior or not. Don't just use const on variables that otherwise don't obviously appear to be treated as constants in the code, as that will just lead to more confusion.

The rumors likely refer to [Static Single Assignment](http://en.wikipedia.org/wiki/Static_single_assignment_form), which is a property of the intermediate language of a given JS implementation. Many optimizations are enabled or enhanced when IRs with this property are used. V8's Crankshaft creates SSA IR, and Turbofan uses it in conjunction with a [sea of nodes](http://static.squarespace.com/static/50030e0ac4aaab8fd03f41b7/50030ec0e4b0c0ebbd07b0e0/50030ec0e4b0c0ebbd07b268/1281379125883/) approach. However, SSA is not an optimization in and of itself, but a property of an IR.

The theory behind "const is faster" is likely that const-declared code is *already in* SSA form – that is, each `const` variable only ever has *one* assignment. Theoretically this means there's less work for the compiler to do. However, the compiler has to run a SSA step no matter what, so I can't imagine it would save *that* much time in the optimization step.

So, `const` is probably not all that much faster. The useful property it *does* have, however, is to indicate to the reader that the value pointed at by a variable **will never change**, and thus the potential that the variable could mutate can be eagerly discarded. This saves some investigation when debugging a complex, stateful program! The reason to use `const` isn't to declare constant *values*, it's to declare constant *bindings* – variables that can never change meaning over the course of a block. I lean towards "if a variable never needs to change, use `const`, and remember that most variables never need to change," though that might be a bit radical.

Of note: `const` should bind the same way as `let` in `for{-in,-of}` loops: a new constant binding + context will be made for each iteration through the target object.

**Comment by getify** [comment]
Appreciate the back story explanation! Cool details. Not sure any of that is appropriate for the level of readership of the book's intended audience. Also sounds like "rumor" implies the right connotation... which is that this is very much speculative implementation dependent details more than exact guaranteed semantics.

Do you think this part is appropriately conveying the why/why-not of `const`?

"...the much more important decision to make is if you intend constant behavior or not. Don't just use const on variables that otherwise don't obviously appear to be treated as constants in the code, as that will just lead to more confusion."

I put in the negative, assuming people know the affirmative. Perhaps it needs the affirmative (as you stated) more explicitly?

**Comment by getify** [comment]
Closing for now. If I'm still missing something, lemme know.
