### ISSUE TITLE
es6 modules and OLOO

### ISSUE THREAD

**Issue by nwmcsween** [getify/You-Dont-Know-JS#523]
It seems an object must be static which conflicts with OLOO thus export default {}; will not work, what is the alternative?

**Comment by getify** [comment]
> seems an object must be static

I don't know which object you mean, but I guess you're talking about an object that is exported on the module's API (since the module's API itself is an implicit object that you don't have access to)? And by static I guess you mean unchanging?

In any case, there's no requirement that an exported object be static in that sense, and no reason you can't have it be a default export.

> which conflicts with OLOO

I don't see how there's any conflict. I don't see why you couldn't have an object on one ES5 module's API be `[[Prototype]]` linked to another object. Perhaps something like:


```js
// foo.js

var obj = { .. };
export default obj;
```

```js
// bar.js

import foo from "foo.js";

var obj = Object.create( foo );
// add to obj definition

export default obj;
```

Now, the thing to remember is that using `[[Prototype]]` delegation (as OLOO does) means all data has to be on the object chain, so you wouldn't be able to share private module member data across the chain, only properties/methods which you put on either `obj` in the above example.
