### ISSUE TITLE
ES6: Use of super and OLOO?

### ISSUE THREAD

**Issue by nwmcsween** [getify/You-Dont-Know-JS#526]
I have this
```javascript
export default Object.assign(Object.create(parent), {
    init(obj, opt) {
        if (!super.init(obj.opt)) ....
    }
});
```
But it seems super doesn't work with OLOO (most likely something I'm not understanding)? Is there someway to go about this without making random initialization names for objects?

**Comment by getify** [comment]
This doesn't really have anything to do with OLOO per se (or ES6 modules).

----

I would point out however that the OLOO design principles would entirely discourage the use of `super`, because the only reason you need that is if you choose to use the same (generic) method name at two+ levels of the object `[[Prototype]]` chain -- what's commonly called "shadowing". OLOO stresses that you should always have unique and descriptive names for methods, so that there's no shadowing, and thus never a need to do something like `super`.

----

I think this is one of the tricky gotchas of `super`... it's statically bound to an object at declaration, and is not "copied" (rebound) when a method is copied over to another object.

Your use of `Object.assign(..)` copies the `init()` method over to the object created by `Object.create(..)`. But its `super` is still bound to the original object (the object literal). So it doesn't resolve to the `[[Prototype]]`-linked object `parent`, but rather the default `Object.prototype`.

TBH, I had not considered this particular gotcha of `super` prior to your question, but this is definitely one of those bad side effects of the decision to make `super` static instead of dynamic (the way `this` is).

**Comment by nwmcsween** [comment]
How can this work? I'm guessing setPrototypeOf, would there be any alternatives?

**Comment by getify** [comment]
you can't use `Object.assign(..)`. You could use `setPrototypeOf(..)` afterwards, or you could do this:

```js
var child = {
    __proto__: parent,
    init(obj, opt) {
        if (!super.init(obj.opt)) ....
    }
});

export default child;
```

**Comment by getify** [comment]
Hope this has helped. :)
