### ISSUE TITLE
same name in different obj in same prototype chain.

### ISSUE THREAD

**Issue by v-k-** [getify/You-Dont-Know-JS#579]
Hi, first I'd like to thank you for these amazing collection of books. I'm quite trough now and this has finally explained JS to me. Amazing job! Really thankful. ;)

I hope you don't mind if I ask here a little question about OLOO.

context: Drawing in a canvas. 
A BaseShape obj holds position, size and weight data
Two linked obj Rect and Circle defines display() functions
I'm creating one or another based on chances.
I'd like to call build() without testing to see which kind it is,
so I did repeated the name of build in these two objects, both linked to BaseShape.
It is working perfectly so far. Is this ok?

in code:

```javascript

BaseShape = {

shapeBuild: 
  function(_x, _y, _w, _h) {
    this.x = _x;
    this.y = _y;
    this.width = _w;
    this.height = _h;
    this.acc = (this.width * this.height / 10000) + 0.2;
    this.speed = 0.0;
  }
  , 

report: 
  function() {

    //console.log(test.x + "  " + test.y + "  " + test.width + "  " + test.height + "\n");
  }
  , 

weight: 
  function() {
    if ((this.y - this.height) < p.windowHeight) {
      this.speed += this.acc;
      this.y += this.speed;
    }
    return this.y > p.windowHeight ? 1 : 0;
  }
};

// new object linked to baseShape
WCircle = Object.create(BaseShape);

//add a display method
WCircle.display = function() {
  p.fill(255, 0, 255);
  p.ellipse(this.x, this.y, this.width, this.height);
};

// convenience to make API clear
WCircle.build = function(a, b, c, d) {
  this.shapeBuild(a, b, c, d);
};
/*
    
 
 
 
 */

// new object linked to baseShape
WRect = Object.create(BaseShape);

//add a display method

// as this has nothing to do with WCircle
// we can safelly repeat the method name?
// aparently yes :)


WRect.display = function() {
  p.fill(255, 0, 255);
  p.rect(this.x, this.y, this.width, this.height);
};

// convenience to make API clear
WRect.build = function(a, b, c, d) {
  this.shapeBuild(a, b, c, d);
};


// LATER

var o = p.random(1) < 0.5 ? Object.create(WCircle) : Object.create(WRect);
o.build(x, y, s, s); // works, builds rects and circles.

```

**Comment by getify** [comment]
The code seems reasonable to me. I would make a few quick comments:

1. I wouldn't call it `BaseShape` because that naming convention feeds into the class inheritance mindset, which OLOO is trying to draw you away from. Rather than thinking about `BaseShape` as a "parent", think of it as a concrete peer object you can delegate to. I would call it `ShapeHelpers` or `ShapeUtilities`, and have your `WCircle` and `WRect` delegate to it.
2. The design of having `BaseShape` (or whatever it's called), followed in the chain by `WRect` (or `WCircle`), followed then in the chain by another object like `o`... this is all very parent/child/instance oriented type design. Even your narrative about selecting either a circle or rectangle at random and then being able to call the `build(..)` (you called it `init(..)` in your OP but I figured out what you meant), that's all extremely in line with class thinking, where an object like `o` has an "isA" relationship to its "parent".

   Could you reorganize this code so it was less about those relationships and more about the objects all being peers of each other?
3. It's not a problem to have method names like `display(..)` or `build(..)` that are common on two peers (like an `o1` and an `o2`), but it is a problem if someday later `o1` and `o2` would be delegating one to the other. Again, same as I said in the previous two points: instead of having these instances of some kind of shape object, think about just making a few objects that are peers of each other.

   It could be that OLOO isn't actually buying you much, at least from the delegation perspective, in the scenario you're building. It's not really the kind of case I'd probably call "typical OLOO". Although, I will say that the simpler OLOO style is better than the more complicated pseudo-classical stuff.

**Comment by v-k-** [comment]
Thanks for the fast reply. Sorry about the `init()` `build` confusion. Fixed that.

>It could be that OLOO isn't actually buying you much

Well my background, not vast, is Java. And this is my 1st attempt with OLOO. Baby steps.
But even before reading the books. I'm at the middle of Types & Grammar. I felt weird about OOP and classes mimics in JS.

This is why I'm trying OLOO.
 
>Could you reorganize this code so it was less about those relationships and more about the objects all being peers of each other?

In fact... maybe not. How would that be? Could you hint me. Like in english or pseudo.

The goal is clear. Shapes that have some common behaviour and data. But different draw methods.
Then create a bunch of them to draw.


    ShapeHelpers { data / weight handling }

    WRect { display } 
    WCircle { display }

And then, the temp object `o` to fill an `array` are really an  instance_sh_  thinking, how should I think about those?

thanks again.

**Comment by getify** [comment]
I think my point is that I don't think your use-case fits into the normal case for what I'd advocate OLOO for. Again, that doesn't make it *bad* to use, but just perhaps not as ideal of an outcome as a different scenario.

Imagine this approach instead:

```js
function display(obj) {
   // use `obj` to draw
}

var o1 = { .. };
display(o1);
```

Here, instead of having the function `display(..)` on a prototype chain so that `o1` can delegate to it, we just call `display(..)` and pass in its context (the `o1` or `o2` or ... ).

Point: it's not clear to me in your case that the complexity of using `this.` everywhere, and prototype chains via `Object.create(..)` is actually buying you much.

In fact, it could be that the "instances" (like `o` in your example) shouldn't be prototype-linked via `Object.create(..)` at all, but `WCircle` / `WRect` / `BaseShape` objects themselves still could ben prototype linked for the purposes of OLOO delegation between them:

```js
var ShapeUtils = { .. };
var WCircle = Object.create(ShapeUtils);
var WRect = Object.create(ShapeUtils);

WCircle.display = function(obj) { .. };
WRect.display = function(obj) { .. };

var o1 = { .. };
var o2 = { .. };

WCircle.display(o1);
```

Ponder that approach and see if you can see how to adapt it to your use-case.

**Comment by v-k-** [comment]
Great thoughts!

 Thanks once more for taking time to look at this. 

I'll think about *this* : )

Tomorrow.  

I'll come back if need.

Have a good night.
