### ISSUE TITLE
"Scope & Closures"- Ch.3 Function Versus Block Scope

### ISSUE THREAD

**Issue by sdras** [getify/You-Dont-Know-JS#594]
Hi, I really enjoy reading these books, they're a wonderful resource, thank you. I did, however, find your explanation of IIFE's a little confusing as it's conflating shadowing and what an IIFE is in general:

> Of course, IIFE's don't need names, necessarily -- the most common form of IIFE is to use an anonymous function expression. While certainly less common, naming an IIFE has all the aforementioned benefits over anonymous function expressions, so it's a good practice to adopt.
> 
> var a = 2;
> (function IIFE(){
>    var a = 3;
>    console.log( a ); // 3
> })();
> console.log( a ); // 2

If we're simply talking about what an IIFE is, shouldn't we use a pared-down example that has no other issues? Seems potentially confusing. Thanks!

**Comment by getify** [comment]
Are you critiquing the `IIFE` name, or the shadowing of `a`?

**Comment by artemist** [comment]
I'm critiquing using a demo that has both at the same time- it seems like people might learn better with an IIFE example that doesn't also have shadowing. There's also no mention of the shadowing here as you're moving through the example, so that's potentially confusing for someone just learning what an IIFE is.

**Comment by getify** [comment]
I feel the shadowing is a way to prove why an IIFE is even necessary. If the inner variable was called `b`, then someone could also ask "why does it even need to be hidden in a scope at all, since it doesn't overlap?" The other ways to **prove** why an IIFE is necessary are much more exotic, such as needing to be able to early-`return`, or temporarily override a `this` binding, etc -- these would also be much more confusing IMO.

So, just showing:

```js
var a = 2;

(function(){
   var b = 10;
   console.log(b);
})();

console.log(a);
```

If I were brand new and learning about scopes, my question would be, "why is the IIFE even needed?"

**Comment by artemist** [comment]
Perhaps, but if that's the reason, could it be stated more explicitly? I don't find that it's inferred enough in the text that "this is a good reason for an IIFE", but maybe that's just me. 

The early-return and overriding this binding seem also to be worth a mention- I think people would get something out of this information as well, even if they are more exotic.

**Comment by getify** [comment]
I appreciate your suggestions. I'll keep this issue thread in mind when I review the text for upcoming "second edition" changes.

**Comment by artemist** [comment]
thank you!

**Comment by getify** [comment]
Closing now that this text has been re-written in the second edition book, so this issue no longer applies.
