### ISSUE TITLE
Chapter 4: Mixing (Up) "Class" Objects - Parasitic Inheritance - Is it possible to inherit another class?

### ISSUE THREAD

**Issue by schatekar** [getify/You-Dont-Know-JS#606]
The following code example is used in [Parasitic Inheritance](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20&%20object%20prototypes/ch4.md#parasitic-inheritance) discussion

```js
// "Traditional JS Class" `Vehicle`
function Vehicle() {
    this.engines = 1;
}
Vehicle.prototype.ignition = function() {
    console.log( "Turning on my engine." );
};
Vehicle.prototype.drive = function() {
    this.ignition();
    console.log( "Steering and moving forward!" );
};

// "Parasitic Class" `Car`
function Car() {
    // first, `car` is a `Vehicle`
    var car = new Vehicle();

    // now, let's modify our `car` to specialize it
    car.wheels = 4;

    // save a privileged reference to `Vehicle::drive()`
    var vehDrive = car.drive;

    // override `Vehicle::drive()`
    car.drive = function() {
        vehDrive.call( this );
        console.log( "Rolling on all " + this.wheels + " wheels!" );
    };

    return car;
}
```

Since the definition of `Vehicle::drive` is overwritten in `Car`, I assume I would not be able to inherit another class from `Vehicle` and expect that `drive` function as defined in base class `Vehicle` is available to my newly inherited class?

**Comment by getify** [comment]
> Since the definition of Vehicle::drive is overwritten in Car

Not exactly. The definition of `car.drive` (notice: object vs class notational syntax) is overwritten, which does absolutely nothing to the `Vehicle::drive` definition. That means if another class "inherits" from `Vehicle`, it will inherit `Vehicle::drive`, not `car.drive`.

**Comment by nickzuber** [comment]
To add to what @getify said, it is also important to understand that the `Vehicle` class defines its `prototype` method `drive`, which means that this `drive` method is baked in to any objects that inherit the `Vehicle` class. 

This is why when we create our `car` object which inherits `Vehicle`, the `car` now has its *own* set of `Vehicle`'s prototypes in its prototype chain. So when we override the `car.drive` method which was inherited from `Vehicle`, it doesn't have any affect on `Vehicle` itself since we're only changing the method which was given to `car` upon its creation.
