### ISSUE TITLE
object oriented or not! at the end of the day. this & Object Prototypes,ch5,"class"

### ISSUE THREAD

**Issue by MehdiRaash** [getify/You-Dont-Know-JS#634]
You are emphasising that JS is labeled as "Object oriented" in the book.
>**In fact, JavaScript is almost unique among languages as perhaps the only language with the right to use the label "object oriented"**, because it's one of a very short list of languages where an object can be created directly, without a class at all.

But on Quora you answered to a [question](https://www.quora.com/What-is-prototypal-inheritance) differently

>So, inheritance vs. behavior delegation is the proper contrast, IMO. To put it another way, **"OO" means "object oriented" (which really means class oriented)**, so to contrast that, I came up with "OLOO", which means "objects linked to other objects". At the end of the day, no matter what syntax hoops you jump through in JS to try to convince yourself you're doing classes, what you end up with is just a bunch of objects that are each linked to another object: behavior delegation.

And as you said "object oriented which means class oriented", definitely JS is not Class oriented.
So I got confused by these two, Could we at the end of the day say JS is an Object Oriented kind of language or not?

**Comment by getify** [comment]
Both statements are correct but focused on different angles. I invented the term "OLOO" because no matter how much JS is really the only deserving language for the "OO" label, history has proven out that people always think of "OO" as being about classes. They don't think about the fact that the first "O" is **object**.

So, to be clear: JS is oriented around objects only, not classes. It'd be nice if we could use the appropriate term for that: "object oriented" (OO). But we can't. So I propose we use "OLOO" instead.

**Comment by MehdiRaash** [comment]
Good, The term "OLOO" is really sufficient in this case cause it also convey that JS deals with Objects rather than Classes.

**Comment by getify** [comment]
Cheers!
