### ISSUE TITLE
In async & performance - Chapter 3, apply/call with 'null' as context.

### ISSUE THREAD

**Issue by mirikle** [getify/You-Dont-Know-JS#656]
In previous chapters, we said that using `null/undefined` as the context variable of `call/apply` will be ignored by some host environments (such as Chrome). But in this chapter we kinda throw that away. Don't know whether we should maintain a consistency of this or not. Anyway, great book!

**Comment by getify** [comment]
> we kinda throw that away

What do you mean? Can you cite some specific examples?

**Comment by mirikle** [comment]
Thanks for your quick reply and sorry for the unclear description!

As an example, in the `Promise.wrap` polyfill-safe guard check, we have

```
           return new Promise( function(resolve,reject){
                fn.apply(
                    null,
                    args.concat( function(err,v){
                ...
```

here we called `apply` with the first argument `null`. This would results as `Window` in Chrome as I tested. There's similar code before this, something like `apply.bind(fn, null)`. That's why I think it's a bit inconsistent with previous chapter's suggestions in which we recommend the use of `Object.create(null)` or `{}`.

**Comment by getify** [comment]
> This would result this within fn be Window in Chrome as I tested

In non-strict mode that's true, but in strict mode (which we should all be using), the `this` will just be `null` or `undefined` in that case.

> previous chapter's suggestions in which we recommend the use of Object.create(null) or {} as the dummy context.

The suggestion of using `{}` or the empty object resulting from `Object.create(null)` is for a function that actually cares about `this` and needs to have its `this` binding normalized to something "safe" so that you're not actually accidentally getting a `this` pointing at some object that it shouldn't. IOW, it's advice for making bindings around functions you control and know how you're using them.

In this case, we can't really know what the end-user of such a polyfill would expect. I think the most conservative step is to use `null` (and assume/hope-for strict mode usage).

But moreover, the use of `null` in such examples is really a short-cut to not complicate understanding of the other overall point with noise that doesn't add anything to the understanding. In this case, the purpose of `Promise.wrap(..)` has nothing to do with `this` behavior, so `null` is a simple way of just not caring.

It's unfortunate that in pre-ES6, there's no way to spread out an array of arguments to a function call without using the `apply(..)`, and that there's no way to use `apply(..)` without passing *something* for `this`. Since I don't care about `this`, I don't want to think about it or code against it.

Thankfully, in ES6, I can get straight to that point and skip the `this` by not using `apply(..)` but rather just spreading args with the `...` operator itself!

**Comment by mirikle** [comment]
I see, thanks for the detailed explanation!
