### ISSUE TITLE
ES6 & Beyond - Chapter 2 - Number Literals

### ISSUE THREAD

**Issue by mirikle** [getify/You-Dont-Know-JS#657]
In the example
```
Number( "052" );            // 52
```
this should be
```
Number( "052" );            // 42
```

**Comment by getify** [comment]
Umm, I don't think so. JS no longer assumes octal with a leading `0`, so that's assumed as base-10, which is in fact just `52`. If you want to coerce in octal, you need to use the more explicit octal literal form `Number( "0o52" )`:

![screen shot 2016-02-06 at 3 55 15 pm](https://cloud.githubusercontent.com/assets/150330/12869608/27ef531a-ccea-11e5-9ada-5b8717e32b03.png)

**Comment by mirikle** [comment]
You are right, I was typing literal `052` in the console. Didn't notice we are testing `Number` here. Closing.
