### ISSUE TITLE
Problem with closures.

### ISSUE THREAD

**Issue by lambainsaan** [getify/You-Dont-Know-JS#693]
```
for (var i=1; i<=5; i++) {
    (function(){
        setTimeout( function timer(){
            console.log( i );
        }, i*1000 );
    })();
}

```
I am confused!

Why this won't work?

I think that engine goes line by line and executes the code line by line after compiling it and in this case the engine will go into the loop then execute all the code in which case the output must be like :- 

0
1
2
3
4

Why it is not waiting for 1000 ms? How for loop is iterating ahead while the function setTimeout is not yet executed?

**Comment by itmitica** [comment]
The `for` loop is executing the IIFE five times.

In it, `setTimeout` is building a future stack of `timer` functions.

Deeper in it, each `timer` function closes over the `i` variable **by reference**.

At the end of the `for` loop, referencing `i` is equal with getting the number `6` value. The `for` loop takes less then a second to execute. Hence, every future `timer` functions execution from the stack occurs after the loop has finished, each referencing the post-for `i` value.

**Comment by getify** [comment]
> Deeper in it, each timer function closes over the i variable by reference

Nope. :) This is a classic case of getting the right answer with the wrong reason. Reference vs value doesn't come into play with closure. Orthogonal. Moreover, a simple value primitive like a number would always be by-value. 

The reason the IIFE as shown doesn't fix anything is because there's still only one `i` being closed over. If the IIFE has its own `i` then each timeout callback closes over a diff `i` thereby preserving the value in each iteration. :)

**Comment by itmitica** [comment]
In the next example, the working example, you pass `i` to the IIFE. `i` being a primitive value, you pass it by value.

**Comment by lambainsaan** [comment]
Got it thanks @getify and @itmitica. I was also thinking like @itmitica , that `i` are referencing to same variable so 6 is printed out 6 times. Closures go against my intuition. :D

**Comment by oldergod** [comment]
| The for loop takes less then a second to execute. Hence, every timer functions execution from the future stack occurs after the loop has finished.

I believe this to be wrong as the timed code will not be executed before the loop is finished, even if the loop takes more than a second because the stack will be stuck at the function/script containing the loop.

**Comment by lambainsaan** [comment]
> the stack will be stuck at the function/script containing the loop.

@oldergod could you please go into the details of this, I am not able to get it completely.

**Comment by oldergod** [comment]
See: https://youtu.be/8aGhZQkoFbQ?t=771

After one second, the browser will indeed add the timed code to the task queue but then, this new task can be executed only when the stack gets empty. The stack can be empty only if the loop has finished .

**Comment by getify** [comment]
No matter how long a piece of code works, it won't be "interrupted" by a shorter timeout being ready to fire. The event loop is where things are scheduled asynchronously and every item gets in line behind everything else waiting. Timeouts will always happen at a minimum on the next event loop tick, never the current one.

**Comment by lambainsaan** [comment]
Thanks now I finally a hold on this thing! 

I have not gone through the Async part of the book series so I didn't know the details of it.

**Comment by itmitica** [comment]
I obviously didn't really knew what I was talking about, so I took the time to properly learn it.

Here it is [JS Slo-Mo: for loop, closure, async callbacks](http://itmitica.github.io/js-slo-mo-for-loop-closures-async-callbacks.html). 

Thank @getify and @oldergod !
