### ISSUE TITLE
Block scoping for try/catch seems incorrect

### ISSUE THREAD

**Issue by addi90** [getify/You-Dont-Know-JS#711]
The line mentioned [here](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch3.md#trycatch) says that `variable declaration in the catch clause of a try/catch to be block-scoped to the catch block`. Based on this the below declaration `a` shouldn't be hoisted and should be scoped to `catch` block only. But it doesn't. See gist [here](https://gist.github.com/addi90/d3535ee4ac83842fd2aa5d5926ee85a6)

I think `try-catch` do not introduce block scope for new declarations in `catch` but just for the `err` error variable. In that case maybe we need to update the wording. Thoughts

**Comment by getify** [comment]
The text says "the variable declaration" which is the `err`, not "any variable declaration" like `var`s added inside the block.

**Comment by addi90** [comment]
OK. Gotcha. But I think in order to avoid any such confusion we can explicitly mention that, maybe accompanied with an example. Thoughts?

**Comment by oldergod** [comment]
Even if the content, as it is, is not wrong. I also think it would be better for the readers to have easy to understand, explicit sentences so they could focus on this very content and not to have to worry about how it is written. Specially when there must be a lot of non native english speakers reading this great series.

**Comment by bcherny** [comment]
just change "variable declaration" to "catch argument"

**Comment by getify** [comment]
I believe I've already addressed [why I don't think this wording needs to change](https://github.com/getify/You-Dont-Know-JS/issues/640#issuecomment-173233171). Even if you don't like the implication of "**the**" vs "**a**", the word "variable" in "variable declaration" doesn't mean `var`. A block-scoped declaration, if that's what you wanted to create, would have to be done with `let` or `const`, not `var`. And if you did one of those inside a `catch` block, you'd indeed get a scoped declaration.

**Comment by bcherny** [comment]
@getify considering the number of people confused by the wording, consider changing it to be more specific. not *every* variable declaration in a catch is block-scoped, just one. that one also happens to be the argument, so it's more clear to refer to it as the "argument", not a generic "variable declaration".

**Comment by getify** [comment]
> considering the number of people confused by the wording

I of course don't want confusing wording, but the challenge is that many times suggestions on these issue threads make the text less clear, not more. As I said, this is not the first time I've considered the section in question, and I do not yet know of a better way to phrase it than the original text. If I had an actionable change here that I think made it clearer, I'd be marking this issue with "second edition" label and addressing it in the upcoming second editions. But so far, I don't feel we've met that mark.

------

If someone is confused about thinking that "variable declaration" means that I'm saying they should be able to do `var x` inside a `catch` block and that be block-scoped, that's a complete misunderstanding of more than just the `catch` semantics. For a declaration to be scoped to any block,`catch` or otherwise, it **has** to be one of the block-scoping declarators (`let` or `const`).

If someone correctly tried to put a `let x` inside the `catch`, it would behave as the OP implied, so my text "variable declaration" would be entirely accurate and verifiable.

So *that* seems to be the real root of the problem, that people are assuming "variable" means `var` when it's clearly already explained in the text that block scoping comes from `let` or `const`, **not** `var`.

> so it's more clear to refer to it as the "argument"

"argument" is definitely not the right term, as it implies all sorts of things like what "argument" means for functions. I haven't heard a better term for `err` in a `catch` header than "declaration".

> not every variable declaration in a catch is block-scoped

This is both true and misleading, in that you could also say "Not every variable declaration is block-scoped". Of course they're not, only block-scope declarations are block-scoped. That's kinda the whole point of the chapter. See above.

**Comment by addi90** [comment]
> So that seems to be the real root of the problem, that people are assuming "variable" means var when it's clearly already explained in the text that block scoping comes from let or const, not var.

But variable declaration pre-ES2015, is done using `var`. So it is confusing that `variable declarations are block scoped in catch block`, when the declaration is done using `var` in ES5

**Comment by getify** [comment]
> variable declarations are block scoped in catch block

That is not what the text says. The text says "**the** variable declaration". I deliberately chose the specific article "the" instead of "a".

------

As I said, I understand the contention, but so far none of the discussion here has led to wording that I feel is clearer. I'm closing the issue for now, because it's not something we need to debate any further. If better wording arises that's actually more accurate, not just different, I will re-consider for second edition.

**Comment by bcherny** [comment]
how about this-

before:
> It's a very little known fact that JavaScript in ES3 specified the variable declaration in the catch clause of a try/catch to be block-scoped to the catch block.

> after:
> It's a very little known fact that JavaScript in ES3 specified the error object passed into the catch clause of a try/catch to be block-scoped to the catch block. Note that any other variable declarations in a catch block are function-scoped like normal.

**Comment by getify** [comment]
That's close. But again, this discussion is presented in the context of introducing ES6 block-level declarations (`let` and `const`). So saying "any other variable declarations" is misleading. To be accurate, the paragraph needs to be more like:

> It's a very little known fact that JavaScript in ES3 specified the error variable declared in the catch clause header of a `try..catch` to be block-scoped to that block. Just like any block, `let` and `const` declarations in the `catch` block would also be block-scoped to that block, but normal `var` declarations are not.

Now, is that clearer while also being accurate? Yes. But I also feel frustrated that it's longer and more clunky. So that's why I've been hesitant to quickly patch the text. It's equally possible that the way to fix this is not to explain all these details here but handle them in other places, wherein the section in question is actually removed from this location.

**Comment by bcherny** [comment]
> Now, is that clearer while also being accurate?

i like my version better, since for some reason the word "declared" makes me think of `var/let/const/function`, instead of binding variables to a function's parameters. i see that you're trying to be specific, but "passed in" gives me a clearer mental image to grab onto.

> It's equally possible that the way to fix this is not to explain all these details here but handle them in other places, wherein the section in question is actually removed from this location.

i like that idea. the tidbit in question is more like js tivia than it is a helpful explanation of block scoping in js. i think however it's worded, it will be more confusing than helpful. it's the kind of language idiosyncrasy you come up against once and google it.
