### ISSUE TITLE
question regarding 'const'

### ISSUE THREAD

**Issue by anirudh-modi** [getify/You-Dont-Know-JS#782]
Hello, 
I was recently going through a blog post of yours on `const`
https://blog.getify.com/constantly-confusing-const/

I have a doubt regarding the code below

````javascript
var a = 1;
const b = a;
a = 2;
console.log(b);
// 1
````

I am not very clear on how and why did the value of `const` never changed? It was initially pointing to the variable `a`, but should not the change in value of `a` must be reflected on const also?

**Comment by kisphp** [comment]
As far as I know, in that snippet you will asign the value of a to b from the current state by copying it. The assignment is not by reference. You are using a constant. It's purpose is to remain unchanged. Right ?

**Comment by andrjuha01** [comment]
Here you don't create a pointer b to variable a, you just assign a value of variable a to the variable b.
So js now do know, that variable b has a value of 1.
And a also has a value of 1.
Now you give value for variable "a" 2.
It does not change the variable b, because it already has it's  own value and it do not have any type of connection now.

**Comment by anirudh-modi** [comment]
Ok, seems a reasonable explanation, I was confused and thought it would pass a reference.
