### ISSUE TITLE
Class inheritance does not imply copies

### ISSUE THREAD

**Issue by dlukes** [getify/You-Dont-Know-JS#786]
> Don't let polymorphism confuse you into thinking a child class is linked to its parent class. A child class instead gets a copy of what it needs from the parent class. Class inheritance implies copies.
>
> &mdash; *YDKJS: this & object prototypes*, Chapter 4

I'm not sure I agree that class inheritance necessarily involves copies, that's really an implementation detail. In languages where a class can't be modified after creation, it makes no practical difference, but in those where it can, like Python or Ruby, there's no reason why you couldn't use links instead of copying, even though these languages aren't prototypal and have quite vanilla class-based OO semantics.

In fact, it's exactly what e.g. Python does, you can modify the behavior of an instance of a child class by monkey-patching the parent class **after the instance was created** (and it doesn't matter whether you access that behavior via `super()` or via a fully inherited method):

```python
class Foo:

    def foo(self):
        return "foo"

    def bar(self):
        return "bar"


class Bar(Foo):

    def foo(self):
        sup = super().foo()
        return sup + ", " + "bar"


b = Bar()
Foo.foo = lambda self: "lambda"
Foo.bar = lambda self: "lambda"
print(b.foo())  # prints "lambda, bar"
print(b.bar())  # prints "lambda"
```

In my mind, the problem with class OO in JS has mainly been that it requires developers to do a lot of the plumbing manually, and allows them to break that plumbing (especially in the case of setting up inheritance chains). So prior to ES6, using class OO in JS was verbose, error-prone and often downright confusing from the point of view of reflection (depending on how you set up your prototype links). These are all points that you make in the text as well, so I'm not pretending to come up with something new here :)

Now that ES6 syntactic sugar has put a more robust layer of abstraction over these issues, I think the most compelling case against class OO in JS is what you say about mental model complexity -- that the same effect can be achieved in JS without needing to think about classes at all.

(Personally, I happen to think there's a counter case to be made in terms of the mindshare the class-based approach has, which makes it easy for newcomers to pick it up compared to the more exotic prototypal patterns, and in terms of clarity of intent as expressed by using dedicated syntactic constructs, but that's a different story.)

At any rate, mental model complexity, along with the points discussed above concerning pre-ES6-compliant code, seems to be a much more unambiguously valid criticism of class OO in JS than the "copying" point on which your current argument happens to hinge rhetorically.

**Comment by venelinpetrov** [comment]
Many JS libraries (if you look at the source) mimic certain Class-oriented-programming behavior (probably taken form Java), which implies exactly copying. This is kind-of the opposite of JS' prototype model. I believe this is what Kyle is pointing us to.

**Comment by getify** [comment]
Yes,  and these libs are mimicking the most common interpretation of inheritance, that of popular langs like c++ and java, where inheritance is static and fixed.

I didn't know python had "retroactive inheritance" but I can say it's not the dominant model for class inheritance among langs and certainly not the one tied most closely to our mental models of inheritance (like blueprint/building or the genetic DNA metaphors).

Most developers, when I describe retroactive inheritance, express that it sounds weird and confusing and backwards.

I believe one could argue that JS's system is more sensible here than python b/c in JS you're just changing an object (not a class). But that still doesn't mean you can reasonably claim that JS's system is a sensible class system.

**Comment by dlukes** [comment]
Doesn't Java exhibit similar behavior with static (class) variables?

```java
public class Main {
    public static void main(String[] args) {
        Foo foo = new Foo();
        System.out.println(foo.bar);
        // change bar on the class
        Foo.bar = 3;
        System.out.println(foo.bar);
    }
}

class Foo {
    public static int bar = 4;
}
```

```sh
$ javac Main.java && java Main
4
3
```

Static members are like prototype properties, instance variables are like own properties. I know precious little about Java, so I'm not sure whether there's a clever workaround to do this with methods, since Java doesn't have first class functions, but it does work with data attributes.

It seems to me that the difference between JavaScript and Java is in how these mechanisms behave w.r.t. to `this`. Java won't let you reference `this` in a static method, i.e. you can't have a class method that manipulates an instance, whereas JavaScript functions don't care how they're declared and can reference `this` as long as the call-site looks right (or via binding).

There's nothing stopping me in JavaScript from defining all "methods" that access `this` inside the "constructor" function, as properties of `this`, and then they'll effectively be private copies of each instance (right?). I just have to be disciplined and do this manually (see the plumbing comment in OP), which means I can easily shoot myself in the foot (at which point all of your comments about a more complicated mental model kick in).

(Defining all methods -- irrespective of whether they access `this` or not -- on the prototype also probably saves memory when you create a lot of "instances", right?)

Never mind, I guess my point is that to my mind, copying vs. non-copying is not the central issue here, so making it the primary angle of the discussion rubs me the wrong way. But that may be because I'm mostly used to dynamic languages which behave the same as JavaScript while happily using "traditional" OO (ruby behaves the same as python) :) If you have experience from training sessions that this way of explaining things actually mostly helps people understand the material, then that's something I won't argue with.

> I believe one could argue that JS's system is more sensible here than python b/c in JS you're just changing an object (not a class).

Classes are objects in Python as well :)

**Comment by venelinpetrov** [comment]
One great point in the book was that you can actually imitate traditional inheritance behavior in JS, but you can't imitate behavior delegation in, say, Java. You can actually imitate whatever you want. So, your example with static and instance methods in Java is of course achievable in JS. The whole point is that you can choose the design pattern in JS and you are not tied to classes only (which is just one of the many design patterns).

**Comment by dlukes** [comment]
I agree, the book does a great job at explaining the semantics of JS and what are the actual mechanisms at play, and shows that this gives enormous flexibility in terms of the programming patterns you can employ. I'm just not entirely comfortable with so much emphasis being put on the copying vs. non-copying behavior, and with non-copying being labeled as unintuitive or downright prohibited w.r.t. to traditional OO (for the reasons cited above -- I think it's part of it as well and different languages have different semantics and restrictions that apply to it).

But hey, if the author knows from experience that this angle works in a teaching setting, then who am I to complain :) Thank you for your time and comments, they helped me understand the original point a little better, as well as clarify my own thoughts!

**Comment by t9md** [comment]
> I'm just not entirely comfortable with so much emphasis being put on the copying vs. non-copying behavior,

I am the man who also felt like this.
Ruby also have **link** to class, although it's OO language.
So for me OO is not necessarily indicate copy-from-class-to-instance.

The book is great, explanation is super clear, thanks so much.
I just wanted to share "me too" impression to @dlukes .

**Comment by anthonyorona** [comment]
I think it is wise not to be so dogmatic in a teaching book -- especially for new programmers who don't realize these are implementation details and not first principles.

**Comment by mangelozzi** [comment]
Firstly thanks for the book, lots of detail on things I didn't know existed.

With Python being such a popular language, I think a large percentage of readers are going to come here confused by the following snippet from the book. Saying that methods/static attributes are `copied` over to new intances sounds hugely inefficient, slow, and a waste of memory. I would think most languages link methods to the class's blue print and bind an instance object to that function when calling it. I am not sure what point this text is trying to make:

### You Don't Know JS Yet (book series) 2nd Edition
#### Chapter 5: Prototypes
##### "Class" Functions

> In class-oriented languages, multiple copies (aka, "instances") of a class can be made, like stamping something out from a mold. As we saw in Chapter 4, this happens because the process of instantiating (or inheriting from) a class means, "copy the behavior plan from that class into a physical object", and this is done again for each new instance.
>
> But in JavaScript, there are no such copy-actions performed. You don't create multiple instances of a class. You can create multiple objects that [[Prototype]] link to a common object. But by default, no copying occurs, and thus these objects don't end up totally separate and disconnected from each other, but rather, quite linked.

How is this different to Python? Python has a class which instances are bound to, which is actually an object, like JS. You can at runtime modiy these class blue print, thus modifying all instances.
Whereas JS has an object which instances are linked to, or a prototype object. Same difference?

Python has multiple inheritance/MRO, which I would think is like linking to multiple prototypes.

**Comment by getify** [comment]
I'm somewhat perplexed that we're still discussing this topic, from a book I wrote 8+ years ago. A book, by the way, that's been surpassed by a [second-edition rewrite, "Objects & Classes"](https://github.com/getify/You-Dont-Know-JS/tree/2nd-ed/objects-classes).

Honestly, I am not going to go back and make changes to a book I published so long ago and subsequently sold many thousands of copies of. Readers are of course free to disagree with what I wrote back then, but what I wrote is set in stone, not a work in progress.

----

That said, let me respond to a few of your comments @mangelozzi:

> With Python being such a popular language

Yes, it's a very popular language. But that doesn't mean it's the most common language that forms developers' impressions of what a `class` is or isn't. In fact, I'd argue that's a shifting target. I think 8+ years ago, C++ and Java were very strong, predominant influences on what developers perceived about various programming concepts, certainly more so than Python. 

But today? No, they aren't nearly as prevalent. That doesn't necessarily mean Python has taken their place, any more than Ruby/Rails might.

Frankly, most JS developers these days probably learn it as their first language, so maybe it doesn't matter what other languages do or don't imply about how classes work as much anymore. But again, almost a decade ago, I think the situation was quite different than today.

In any case, I'd be far more interested in discussions over what I wrote about `class` a few months ago, compared to what I wrote about it almost a decade ago.

> Saying that methods/static attributes are copied over to new intances sounds hugely inefficient, slow, and a waste of memory.

Those assertions were far less about the actual implementation details -- indeed, C++ I think uses some sort of virtual table for dynamic lookups... it's not the prototype chain since the table is not run-time mutable, but it's not as "inefficient" as that naive interpretation would have implied.

The majority of the point was the mental model. I argue that class-oriented design thinking (regardless of syntax or implementation details) encourages you to think of the relationships between things (classes, subclasses, and instances) as static compile time definitions, as opposed to dynamic re-organizable relationships. That's what "copy" versus "link" distinctions were getting at.

Even in languages like Ruby and (I guess?) Python where the class is an object that can be mutated after "inheritance", I don't think I've seen any evidence to suggest that the predominant mental models these languages encourage, and are considered best practice styles and idioms, are any less "static" than the mental models that languages like Java and C++ encourage.

Of course, I don't spend any of my mental energy learning or following what's happening in those languages, so I might be completely wrong. But I feel like there'd likely have been some surfacing of "dynamic/retroactive inheritance is awesome!" waves of developer enthusiasm that would have spilled over from those languages, if that was actually something that's happening. So I remain comfortable in my assumption that it's not in fact a common practice.

And since that's likely the case (more than not), I think my original points stand: that JS (prior to the ubiquity of the `class` keyword) stood somewhat apart from the other languages, in that what we were wiring up to emulate classes were entirely mutable objects, and thus it was quite a bit more common that JS "classes" were more dynamic in their nature than the traditional "static" class hierarchies of other languages.

Most of that is rather moot now, anyway. JS `class` is absolutely more "static" than the prototypal-class pattern that preceded it. That's further evidence that in fact, class-oriented thinking is pretty strongly tied to modeling inheritance relationships as fixed/static things rather than as lines to be mixed and reconnected at will at run-time.

So I feel rather vindicated in watching how `class` has played out in JS.

I think it presents a rather stark contrast: if you prefer dynamicism, I think you shy away from `class`. But if you prefer the clear-cut lines of inheritance and class-oriented thinking, `class` is probably one of your preferred features of the language.

I know where *I* fall on that spectrum. And all I ever wanted to do was help developers think more critically for themselves about what they prefer, rather than falling into a syntax or paradigm *by default* or *by accident*.

I think what I wrote back then accomplished that, to an extent that I am comfortable with and have no regrets. And I think what I've written much more recently about the topic reflects that evolution.

So... to summarize: I don't regret or plan to retract any of what I said before about classes and JS. But I'd much rather we stop beating old dead horses and instead talk about what JS *is* now, and what the reality of `class` has solidified in the language.
