### ISSUE TITLE
Feedback on this & object prototypes ch. 1

### ISSUE THREAD

**Issue by kaycebasques** [getify/You-Dont-Know-JS#790]
Great series. Helping me a lot in gaining a deep understanding of JS.

I have a minor point of feedback for the following code snippet from "this & object prototpyes", chapter 1: 

```
function foo(num) {
    console.log( "foo: " + num );

    // keep track of how many times `foo` is called
    this.count++;
}

foo.count = 0;

var i;

for (i=0; i<10; i++) {
    if (i > 5) {
        foo( i );
    }
}
// foo: 6
// foo: 7
// foo: 8
// foo: 9

// how many times was `foo` called?
console.log( foo.count ); // 0 -- WTF?
```

I don't see the value of the `if` statement. It just slowed down my comprehension of the code, for no reason related to the topic of the chapter. Granted, it only took me a few seconds more to comprehend, but I went paranoid for a couple moments trying to understand how that snippet of code related to the topic at hand, followed by frustration because it wasn't actually relevant.

**Comment by getify** [comment]
Without the `if` statement, there would be no reason to want to track how many times `foo(..)` was called, because it would obviously always be called the same number of times as the loop iterates (ie, `10`). The intent was to illustrate the case where you want to inspect how many times a function was called when you can't necessarily know that in advance (because of runtime conditions -- like the `if`).
