### ISSUE TITLE
[this & Object Prototypes] Ch5: Prototypes

### ISSUE THREAD

**Issue by anirudh-modi** [getify/You-Dont-Know-JS#798]
It was said that every object has its own `[[Prototype]]`, and it is linked to some object in turn. And the end of the chain is `Object.prototype` object. 

My doubt is if we look at the `Object` itself, it's `Object.[[Prototype]]` actually points to `Function.prototype` and the `Function.[[Prototype]]` actually points back to the `Function.prototype`.

I am a bit confused here, why is the `Object.[[Prototype]]` &  `Function.[[Prototype]]` are both pointing to `Function.prototype`, 

should not the `Function.[[Prototype]]` actually `Object.prototype`, as functions are sub-type of object?

And should not `Object.[[Prototype]]` point to `Object.prototype`?

**Comment by getify** [comment]
`Object` is a function, so it's clear that its prototype, as will all other functions in JS, would be `Function.prototype`. The same for `Function`, which is itself a function. `Function.prototype` is the `Empty` function, from which all other functions derive from.

IOW, functions all derive from `Function.prototype` and all other objects derive from `Object.prototype`.

**However**, `Function.prototype.[[Prototype]]` (aka `Empty.[[Prototype]]` is in fact `Object.prototype`, so that's how, ultimately, all functions are objects.

See [the diagram here](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20&%20object%20prototypes/ch6.md#mental-models-compared) to verify these things.

**Comment by anirudh-modi** [comment]
> `Function.prototype` is the `Empty` function

In the section ["Class" Functions](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch5.md#class-functions) of Chapter 5, it was mentioned that :
> All functions by default get a public, non-enumerable (see Chapter 3) property on them called prototype, which points at an otherwise arbitrary object

So, If `Function.prototype` aka `Empty` is a function, should not the `Empty` function have a `Empty.prototype` property?

**Comment by anirudh-modi** [comment]
This is clear that why `Object.[[Prototype]]` is pointing to `Function.prototype`. 

> `Function.prototype` is the `Empty` function

In the section ["Class" Functions](https://github.com/getify/You-Dont-Know-JS/blob/master/this%20%26%20object%20prototypes/ch5.md#class-functions) of Chapter 5, it was mentioned that :
> All functions by default get a public, non-enumerable (see Chapter 3) property on them called prototype, which points at an otherwise arbitrary object

So, If `Function.prototype` aka `Empty` is a function, should not the `Empty` function have a `Empty.prototype` property?

**Comment by getify** [comment]
Neither `Empty` nor `Object.prototype` have a `. prototype`. Why?  I didn't design JS so I don't really know.

But I can guess... `Object.prototype` doesn't need one because there's nowhere else to go looking, and `Empty` doesn't need one because you never instantiate it like `new Empty()` (or rather, `new Function.prototype()`). That's just how it is.

**Comment by anirudh-modi** [comment]
Ok. Thanks for the explanation. 👍

**Comment by anirudh-modi** [comment]
I guess I was confusing myself with `function` and `Function`, 

this means that `Array.prototype` is an `Empty Array`? which has the methods like `.push` ,`.pop`, etc?
