### ISSUE TITLE
Async & Performance - ch1 - Event Loop

### ISSUE THREAD

**Issue by bedenko** [getify/You-Dont-Know-JS#821]
Code provided does not go with description.

For example:
In description we see```setTimeout(..)```, but this is not found in code.

**Comment by getify** [comment]
IIUC, the code snippet you're referring to is described immediately before it as "fake'ish code" because it's not real, just conceptual pseudo-code. Moreover, the description below this snippet that mentions `setTimeout(..)` is not describing the snippet, but describing a scenario in real code (not the snippet) that would end up pushing data into the algorithm described in the snippet in question.

It's a very different thing to talk about code that interacts with other code, and to talk about the code itself. The former is what the text is doing, not the latter.

**Comment by bedenko** [comment]
Oh, thank you for explanation!
