### ISSUE TITLE
Module and OLOO usage

### ISSUE THREAD

**Issue by berkzorlu** [getify/You-Dont-Know-JS#825]
I've been reading about the module pattern, as well as OLOO. I also looked at how you're organizing your files in your cloud-sweeper repository as an example. It appears that you primarily use modules to organize everything, with only a few of them containing OLOO's. I'm already convinced to use OLOO as opposed to the prototype pattern.

I understand that the module pattern is used basically as a container with its own scope. And OLOO is a better alternative to the prototype pattern, and uses delegation.

Here's where I need some clarification:
When is it a good idea to use OLOO's within a module (or in general)? A lot of the modules I saw in your repository have states (by that I mean variables and objects, in addition to the functions). Given that, what benefits does an OLOO present over a module with state, other than the ability to delegate through linking, and the ability to create multiple "instances"? Basically I'm looking to understand the bigger picture of when and how I should be utilizing both patterns.

Thanks in advance :)

**Comment by getify** [comment]
OLOO and Modules are really very different approaches to organizing code. I don't recommend trying to mix them. I use modules for probably 95% or more of my code.

When I find that there's a place that 2-3 different objects (not modules, really) need to cooperate with each other closely (meaning, not just one calling the other, but all calling each other circularly), that's when I reach for OLOO, because delegation is a form of virtual composition. Two or three objects end up essentially composed/mixed together dynamically during delegation so that all that circular interaction is easy.

So look for cases where you have that kind of pattern, and use OLOO instead of modules. Otherwise, stick with modules.

**Comment by berkzorlu** [comment]
Thanks for your response. That's helpful. And thanks for all you do.
