### ISSUE TITLE
Up & Going - Chapter 2 - Prototypes: demonstrate the prototype linkage from bar to foo

### ISSUE THREAD

**Issue by jlem** [getify/You-Dont-Know-JS#846]
The current example looks like this:

```javascript
var foo = {
    a: 42
};

// create `bar` and link it to `foo`
var bar = Object.create( foo );

bar.b = "hello world";

bar.b;      // "hello world"
bar.a;      // 42 <-- delegated to `foo`
```

And it's stated that `bar.a` is prototypically linked to `foo.a`.

However, from the code snippet, it's not really clear that this is the case. A reader might conclude that `Object.create( foo )` is just making a copy of `foo`, and now `bar.a` is independent of `foo.a`.

Thus in order to actually demonstrate the link in code, it would be worth adding two extra lines to the example:

```javascript
var foo = {
    a: 42
};

// create `bar` and link it to `foo`
var bar = Object.create( foo );

bar.b = "hello world";

bar.b;      // "hello world"
bar.a;      // 42 <-- delegated to `foo`

foo.a = 55;

bar.a;     // 55 <-- changes to foo.a reflect in bar.a as well
```

**Comment by getify** [comment]
I understand and appreciate the point here. However, this comment "changes to foo.a reflect in bar.a as well" actually confuses things more. The more accurate statement would be "bar.a is actually foo.a via delegation".

I cover the copy-vs-delegate distinction in detail later in the book series. I want to keep this part relatively simple, since the intended audience is brand new learners of JS.

The comment currently states that the access of `bar.a` is delegation. So, I don't think the text leaves this point unclear. If a reader doubts that what the text says is true, your suggested snippet could "prove" it to them, but that's not the tone I'm trying to take in this early beginner title. I do that kind of thing all throughout the later titles.
