### ISSUE TITLE
Up & going equality 3 simple rules 

### ISSUE THREAD

**Issue by flaviafm** [getify/You-Dont-Know-JS#866]
Hi, I just finish the Up and Going book and now Javascript makes much more sense to me. Thank you. 

However when talking about Equality you give the example of "42" == 42  is true and "42" === 42 is false. So far no issues with it.Understood why how you got there. Few lines below (page 38) you mention the your few simple rules:

• If either value (aka side) in a comparison could be the true or false value, avoid == and use ===.
• If either value in a comparison could be of these specific values (0, "", or []—empty array), avoid == and use ===.
• In all other cases, you’re safe to use ==. Not only is it safe, but in many cases it simplifies your code in a way that improves read‐ ability.

How is "42" == 42 would be safe? The third rule should have better explanation?

Thank you

**Comment by emealcubo** [comment]
It depends on the needs of your application.

If you need 42 to be a numerical because you're going to make some operations on it, you should use ===.
But if you're just gonna display the value, you could safely use ==.

You need to ask yourself "do I really need this variable to be of this certain type?".

**Comment by getify** [comment]
> How is "42" == 42 would be safe?

First, I agree with @emealcubo. Second, I think `42` and `"42"` are clearly just the same value represented in different types. If you're OK with the different representations of the same value, `==` is your friend. If you really need to distinguish between `42` and `"42"`, that's fine too, just don't use `==` coercive equality.

In other words, the context of the overall advice is, if you *want coercion*, here's how to do it safely. If you don't, don't use it.

Does that help?

**Comment by flaviafm** [comment]
Thank you for quick response. It helped and I agree with,  Maybe I wasn't very clear asking why the equality will be safe. My question is more because if you are a novice or someone coming from other language (my case) reading the example and the rules can be confusing. I was initially confused, then reading chapter 1 again and trying in browser it became clear and really great 3 simple rule. Maybe what missed in while reading it was exactly what you wrote "If you're OK with the different representations of the same value, == is your friend. If you really need to distinguish between 42 and "42", that's fine too, just don't use == coercive equality."

Saying the above in any way I want to say how to write the book, it just a feedback.

**Comment by getify** [comment]
Thanks for the feedback! :)

**Comment by getify** [comment]
Re-opening because I'm going to consider this for second edition updates.

**Comment by venelinpetrov** [comment]
@flaviafm, a practical example: if you read a range/numeric input value, it's clear that it can produce only numbers, but `.value` returns them as strings. If you don't want to type cast each time, you can use `==`, because it coerce for you. Another example is: when you know the return type of a function. It's just redundant to use `===` if you know it returns one and only one type of values.

**Comment by getify** [comment]
@venelinpetrov great points, thanks! :)

**Comment by shawndube** [comment]
If there are quirks in how the coercion occurs (which might affect your expected outcome), may be worth mentioning too. Thx for all you do @getify !

**Comment by jmar777** [comment]
One additional quirk to be aware of with the form value example is that `input.value` for an empty field will give you `""`, and `"" == 0` (which would be covered by the "second rule" in the OP). That might sometimes be semantically equivalent, but certainly not always.

`<opinion>`One more rule that might be worth adding: "If someone other than you who hasn't committed all the previous rules to memory might maintain this code one day, then use `===`. :)`</opinion>`

**Comment by getify** [comment]
The rules would already disallow you doing 'anything == 0' so you should never get into the "" == 0 case in the first place.

I maintain that anyone can learn these few simple rules I've distilled and laid out. Furthermore, it's literally impossible to write code that's perfectly context-free understandable, so I think it's a reasonable bar to set.

**Comment by jmar777** [comment]
> The rules would already disallow you doing 'anything == 0' so you should never get into the "" == 0 case in the first place.

Ahh, good point. I was focusing too much on the `input.value` operand, I guess.

> I maintain that anyone can learn these few simple rules I've distilled and laid out. Furthermore, it's literally impossible to write code that's perfectly context-free understandable, so I think it's a reasonable bar to set.

I don't find that unreasonable by any means, and I'm not overly dogmatic on my point. I just think it's worth observing how `==` vs. `===` is such a reoccurring theme in wtfjs-style posts, and despite having stable semantics since the mid-90's, there's still frequent confusion around it. That's purely anecdotal, but there are a lot of such anecdotes, and I can't really think of many real-world scenarios where I've found readability decreased by not just using `===`.  `/2-cents`

**Comment by vandal-x** [comment]
Hi @getify 
Question about second rule: how we can compare some value with empty array if it compares by reference (like the other objects)?

**Comment by vandal-x** [comment]
Thanks for reply.
Maybe I misunderstood this rule, but is reads like "if value can be empty array use `===`". Maybe it needs more accuracy?

**Comment by getify** [comment]
No the rule is, "if it's an empty array, don't use `==`." And the context of the rules are, "If you're hoping to do a coercive comparison, .... " In the case of a deep equality, that's not coercive comparison, so these rules don't apply.

**Comment by getify** [comment]
Closing since "Up & Going" was replaced with the new "Get Started" book for second edition, so this issue is no longer applicable.
