### ISSUE TITLE
"this & object prototypes": Object.setPrototypeOf performance

### ISSUE THREAD

**Issue by Olgagr** [getify/You-Dont-Know-JS#953]
> Moreover, as of ES6, the clunkier syntax you use (like for the AuthController definition), where you're assigning properties individually and not using an object literal, can be re-written using an object literal (so that you can use concise methods), and you can just modify that object's [[Prototype]] with Object.setPrototypeOf(..)

In the MDN docs for the standard, we can find this warning:

> Warning: Changing the [[Prototype]] of an object is, by the nature of how modern JavaScript engines optimize property accesses, a very slow operation, in every browser and JavaScript engine. The effects on performance of altering inheritance are subtle and far-flung, and are not limited to simply the time spent in obj.__proto__ = ... statement, but may extend to any code that has access to any object whose [[Prototype]] has been altered. If you care about performance you should avoid setting the [[Prototype]] of an object. Instead, create a new object with the desired [[Prototype]] using Object.create().

I'm wondering if this is really so expensive operation, this nicer syntax it gives us is worth of using _setPrototypeOf_ ?

**Comment by getify** [comment]
I don't specifically agree with those comments as listed on MDN. In a sense, changing the prototype undoes some caching/optimizations the browser may have otherwise done to shortcut the lookups, but the same would also be true of adding, updating, or removing properties on any object in the chain. If the point is that dynamicism is slower, it is. But I'm not aware of any particular weakness that changing the prototype would have.
