### ISSUE TITLE
Implicit Example of Shadowing

### ISSUE THREAD

**Issue by couryrr** [getify/You-Dont-Know-JS#960]
For the example you have on implicit shadowing, below slightly changed, you call out the increment as implicit shadowing. The increment operation itself is implicit for `n =  n + 1`.

While the operation of increment is implicitly an assignment I do not think that this is implicit shadowing so long as there is an understanding of the implicit assignment of `++` or `--`.

It is not a bad note but based on strictly following the logic of this chapter I would have been floored had `base` been updated.

```
let base = {a:2, foo: "bar"};
let child = Object.create(base);

console.log(child.hasOwnProperty("a")); // False

child.a++;
// implicit for: child.a = child.a+1

console.log(child.hasOwnProperty("a")); //True
console.log(child.a); //3
```

**Comment by getify** [comment]
Setting aside `child.a++`, I find `child.a = child.a + 1` confusing in its implicit shadowing. Even simplify it further: `child.a = child.a`. That statement should be a no-op like `a = a` is. But it's not, it's implicit shadowing. I don't find that intuitive at all.

The point of this section and note is to explain that which I find non-intuitive. For those that do find it intuitive, should be harmless to reinforce that which they already "get", no?

**Comment by couryrr** [comment]
I would not say that `child.a = child.a` is the same as using the increment there is action. However your statement did expose something I at the very least find non-intuitive if you do with the same code as above `child.a = child.a` that is shadowed on the `child` object.

I would agree that there is no harm of keeping this in the end I just guess calling it implicit shadowing was the thorn for me it is really the `++` operation that does a implicit assignment.

**Comment by getify** [comment]
`++` **does** have an implicit assignment... but even an explicit assignment creates an implicit shadowing: in `child.a = child.a`, the right side gets `a` from the prototype chain, whereas the left side (which looks the same) sets directly on `child`, creating the shadowing.

I call this "implicit" shadowing because the `child.a` reference is the same on both sides (regardless of whether there's a `+ 1` or not) but it resolves to different locations.

So perhaps the most accurate note would have been "`++` is an implicit assignment that creates an implicit shadowing." Shrugs. :)

**Comment by couryrr** [comment]
Alright I feel nit picky now. I am just going to keep reading. Thanks again for the great material!

**Comment by determin1st** [comment]
khmm, what so "implicit" there? everything is determined
