### ISSUE TITLE
Up&Going Expressions Example

### ISSUE THREAD

**Issue by gminovska** [getify/You-Dont-Know-JS#991]
Hi @getify! Big fan of your work here. Purchased your books and the videos, you are an amazing wealth of knowledge. Thank you for all your work.

Now, in the Up & Going book you give the example: `a = b * 2;` and say this statement has 4 expressions. The variable a is not counted as an expression in the book.

This differs from the Frontend Masters video in which you make an ad hoc statement and count the expressions. In the video, you make a self-correction and state that the left hand side is also an expression. I include a link to that section of the video: http://bit.do/expressions-example

With that in mind, the book example should be corrected and count the variable a as an expression as well, so the example has 5, not 4 expressions in total.

**Comment by langpavel** [comment]
Hi. In this case I must say that this is more complicated. Look at grammar.It can be expanded to right side only or at whole statement.  So, it is really important in which score you are looking.

**Comment by eebann** [comment]
its 4 and correct

**Comment by travismchan** [comment]
I'm leaning towards 5... :)

**Comment by getify** [comment]
Technically left-hand sides are "expressions" in the sense that they are resolved first (at run time) to make sure they are legal assignment targets. For example:

```js
2 = 1;
```

That's valid JS syntax, though it fails at run time, because the `2` on the left hand side is resolved and isn't a valid target.

Also, ES6 added destructuring, in which case the left-hand side is a more complex assignment "pattern", not just a simple variable. That's not exactly an "expression" per se, but it's also not just simple variables on the left-hand side either.

These nuanced details are inappropriate to clutter a beginner text like Up & Going, though.

It's unfortunate that there's "disagreement" there between the book and my video, but these discussions are very different contexts.
