### ISSUE TITLE
You Don't Know JS: Async & Performance Chapter 4: A question on example in Interleaving

### ISSUE THREAD

**Issue by mondwan** [getify/You-Dont-Know-JS#996]
Hello @getify , thanks for your great books firstly.

Recently, I am confused with example in interleaving. My first computation is

```
console.log( a, b );	// 12 24
```

while actual answer is

```
console.log( a, b );	// 12 18
```

After digging a while, I believe reasons for being 18 instead of 24 is this tricky statement in `s2`

```
b = a * (yield 2);
```

`yield` behinds `a` which resolved as `a=9` before `s1()` get involved (which makes `a=12`). Therefore, `b` equals `18` instead of `24`.

Do my guest correct? It will be great if there are descriptions for detail run with this example.

Thanks again.

**Comment by getify** [comment]
Correct... at the moment that `yield 2` happens, `a` has already been resolved to `9`, even though it's subsequently changed to `12`.

The confusion you're experiencing is kinda the whole point of the example, to point out that threaded interleaving is a nightmare. It's tricky to get right, even for me, and I wrote it. Took me about 5 minutes just now to refresh myself on what was happening.

**Comment by getify** [comment]
Another example of this effect can be seen even without generators:

![screen shot 2017-03-26 at 10 54 15 am](https://cloud.githubusercontent.com/assets/150330/24332816/99335dfa-1212-11e7-9840-1227c278d03c.png)

As you can see, the `b = ..` reassignment doesn't happen until after the `b * 2` has already been calculated, so that expression is `6`. If those two expressions reversed order, `b` would already be `7` when multiplied by `2`, so the value of `c` would be `21` instead of `13`.

**Comment by mondwan** [comment]
Interesting. This sounds black magic. Had this rule been covered in the
Grammer book? It seems I have not read that before.

2017年3月26日 23:58，"Kyle Simpson" <notifications@github.com>寫道：

**Comment by mondwan** [comment]
Another problem inspired by this positioning problem. It is possible to
force the rhs value runs first?

Actually, I have tried to eliminate the brackets of yield which is a syntax
error (from jsfiddler) and double brackets ((yield 2)). Result is still 18.

To make it 24, the only way is switching their position?

(Yield 2) * a

2017年3月26日 23:53，"Kyle Simpson" <notifications@github.com>寫道：

Correct... at the moment that yield 2 happens, a has already been resolved
to 9, even though it's subsequently changed to 12.

The confusion you're experiencing is kinda the whole point of the example,
to point out that threaded interleaving is a nightmare. It's tricky to get
right, even for me, and I wrote it. Took me about 5 minutes just now to
refresh myself on what was happening.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/getify/You-Dont-Know-JS/issues/996#issuecomment-289292888>,
or mute the thread

**Comment by getify** [comment]
The "types & grammar" book covers (ch5 IIRC) the notion of left-to-right vs right-to-left, and also the behavior of left-associative vs right-associative operators.

**Comment by mondwan** [comment]
I guess I need helps on understanding concepts between Operator precedences
and associative in your example.

Precedence of brackets is higher than the addition and multiplication
operator. So, why the brackets one would not be processed first?

var c = b * 2 + (b = a + 5)

Is it because statement are processed from left to right due to left
associative of addition and multiplication operators?

Therefore, order of execution orders are

- Resolve b
- b * 2 // C1
- Resolve (b = a + 5)
   - Resolve a // = is right associative
   - a + 5
   - b = a + 5 //C2
- C1 + C2

Or, in other words​, precedence of associative is higher than the operators?

2017年3月27日 00:20，"Kyle Simpson" <notifications@github.com>寫道：

**Comment by legodude17** [comment]
The `+` is the top level operator, so it gets resolved first. The part with the parens is the right child of the `+`. Did that answer your question?

**Comment by mondwan** [comment]
Why `+` is the top level one?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

Bracket should be the highest one according to the link above.

**Comment by legodude17** [comment]
The parens are inside the `+`, because the `+` is operating on the result of the parens.

**Comment by mondwan** [comment]
Honestly, I cannot tell what I am confusing about. I am just feeling odd about why bracket does not resolved at first priority.

For example, below is a simple arithmetic statement

```
1 + (2 + 3) * 4
```

Before this thread, according to my understanding, steps for resolving on this statement

* (2 + 3) => 5
* 1 + 5 * 4
* 1 + 20
* 21

The token with bracket should get resolved in first priority.

However, after this thread, steps sound like following,

* 1
* 1 + ((2 + 3) * 4)
* 1 + (5 * 4)
* 1 + 20
* 21

The order of resolve is always from left to right no matter where the bracket is. Is it true OR do I miss something about that? Although this is a subtle problem, it really puzzles my mind. LOL

**Comment by getify** [comment]
> feeling odd about why bracket does not resolved at first priority.

That's not what parenthesis do -- in any language, AFAIK, but definitely not in JS. Parenthesis are about overriding default operator precedence or operator association (aka grouping). They're not like `!important` in CSS telling the engine "hey, this thing is really important, do it first."

Operator precedence doesn't come into play when you have `x + y`. There's only one operator. When operator precedence (and associativity) is not relevant, expressions (`x` and `y`) will always be done in left to right order. `x + (y)` **doesn't** make `y` get evaluated first. It's just strictly left-to-right.

You have to have two operators for operator precedence (or associativity) to be relevant. So, with `x + y * z`, since `*` is more precedent than `+`, it means the `y * z` happens first, then the `x + ..`. If you want to override that, you can do `(x + y) * z`. Inside `(x + y)`, the left-to-right still applies as above.

And comparing `(x + y)` to `z`, those two expressions will still execute in left-to-right order, and then be multiplied. If we instead had `z * (x + y)`, those expressions still are processed left-to-right. The `( .. )` doesn't make `(x + y)` evaluate first.

So, that's operator precedence. It overrides which operator gets executed first if two adjacent operators have different precedence. It doesn't affect left-to-right at all.

For operator associativity, we also must have more than one operator to be relevant, and our concern is how adjacent operators are grouped if they have the same precedence. For example: `x + y + z`.

The `+` operator is "left associative", meaning the implied grouping happens with a bias to the left. IOW, that expression would be interpreted like this: `(x + y) + z`. The processing happens left-to-right: `x` is evaluated, then `y`, then `z`, then `x + y`, then `.. + z`. If `+` were right-associative, the expression would be interpreted like `x + (y + z)`. But, the processing of the two expressions **still happens left-to-right**: `x` is evaluated, then `y`, then `z`, then `y + z`, then `x + ..`.

Now, with simple `+` addition (or even concatenation), associativity is irrelevant because the two interpretations are indistinguishable. That's actually because such operations are mathematically associative.

But some operators aren't left-associative. Ternary for example, is in fact right-associative, meaning the grouping will bias to the right when precedence is otherwise considered equal.

Consider: `a ? b : c ? d : e`. That could be interpreted as `(a ? b : c)` ? d : e` or as `a ? b : (c ? d : e)`. The second one is the correct interpretation, because of the right-associativity.

But, the processing **will still be left-to-right**. That never changes. In `a ? b : c ? d : e`, `a` is evaluated first -- not `(c ? d : e)` despite the implied `( .. )`. And even if you actually put the `( .. )` in, it's still not going to be evaluated before `a`.

This is criticial for operator short-circuiting, actually. If `a` is truthy, then `b` is evaluated and used, and the `(c ? d : e)` doesn't even need to be evaluated at all, just like an `else` block doesn't get evaluated if the `if` block is.

**Comment by mondwan** [comment]
Thanks for the detail explanation. It really helps me on distinguishing issues between left to right evaluations and operator precedence especially the last short-circuiting example.

By the way, ternary example if not properly format

Should be this

```
`(a ? b : c) ? d : e` or as  `a ? b : (c ? d : e)`
```

which comes

`(a ? b : c) ? d : e` or as  `a ? b : (c ? d : e)`
