### ISSUE TITLE
"this & object prototypes": Chapter 2 'Implicitly Lost' question about implicit assignments.

### ISSUE THREAD

**Issue by robbporto** [getify/You-Dont-Know-JS#998]
In this chapter, it's said:

> Parameter passing is just an implicit assignment, and since we're passing a function, it's an implicit reference assignment, so the end result is the same as the previous snippet.

What exactly is an implicit assignment? What about an implicit reference assignment?

**Comment by getify** [comment]
By "implicit assignment", I mean a `parameter = argument` assignment that happens but which we don't syntactically see. When I say "reference assignment", I mean "copy of reference assigned".

**Comment by robbporto** [comment]
Thanks for the explanation, @getify. It took me almost an hour to understand what you said. I'll try to explain what I understood for future reference in case someone needs. Please, correct me if I said something wrong. If everything's right, you can close this issue.

--

Consider this code (it's the same used in the chapter mentioned on the title of this issue):

```
function foo() {
	console.log( this.a );
}

function doFoo(fn) {
	// `fn` is just another reference to `foo`

	fn(); // <-- call-site!
}

var obj = {
	a: 2,
	foo: foo
};

var a = "oops, global"; // `a` also property on global object

doFoo( obj.foo ); // "oops, global"
```

When @getify says: _By "implicit assignment", I mean a parameter = argument assignment that happens but which we don't syntactically see._, it means that we're not doing this **explicitly** in the `doFoo` function:

```
function doFoo(fn) {
    fn = function() { // NOT implicit assignment.
        console.log(this.a);
    }

    fn(); // <-- call-site!
}
```

And the part: _"reference assignment" is a "copy of reference assigned"_ means we're "copying" the function `foo` to inside of the `doFoo` function just like I wrote above.

**Comment by getify** [comment]
> it means that we're not doing this explicitly in the doFoo function:

Yes, mostly. Precisely, I mean this:

```js
function doFoo(fn) {
	/* this part is hidden and thus "implicit" */
	fn = obj.foo;
	/* ---------------- */

	fn(); // <-- call-site!
}

doFoo( obj.foo );
```

> we're "copying" the function foo to inside of the doFoo function just like I wrote above.

Eh, not quite. It means that a reference (not the actual function but a "pointer" to it) is what is copied when the `fn = obj.foo` occurs. Functions never get copied, they cannot be duplicated, because they are never held by value but by reference. So when you assign the reference, you're copying the reference, not the function itself.

------

```js
var a = 2;
var b;

// value is copied:
b = a;
a = 3;

a;   // 3
b;   // 2
```

In the above snippet, the value was copied from `a` to `b`, which is why when `a` is then re-assigned, it has no effect on what `b` is holding.

Now consider:

```js
var a = { x: 1 };
var b;

// reference is copied:
b = a;
a.x = 3;

a;    // {x: 3}
b;    // {x: 3}
```

In this second snippet, `a` holds the object by reference, and so when `b = a` occurs, that's a **copy of the reference**, not of the object value itself. That's why when you mutate the object with `a.x = 3`, both `a` and `b` are still seeing that same object, via their mutual copies of the reference to the same shared object.

Hope that clears it up.

**Comment by robbporto** [comment]
Very clear now, @getify. Thank you.
